### ISSUE TITLE
Can't locate WUBlastSearchEngine.pm

### ISSUE THREAD

**Issue by ohan-Bioinfo** [Dfam-consortium/RepeatModeler#106]
```
Can't locate WUBlastSearchEngine.pm in @INC (you may need to install the WUBlastSearchEngine module) (@INC contains: /usr/local/bin /Users/ohon_ad/Documents/Tools/RepeatModeler/RepeatModeler-2.0.1 /usr/local/Cellar/perl/5.30.3/lib/perl5/site_perl/5.30.3/darwin-thread-multi-2level /usr/local/Cellar/perl/5.30.3/lib/perl5/site_perl/5.30.3 /usr/local/Cellar/perl/5.30.3/lib/perl5/5.30.3/darwin-thread-multi-2level /usr/local/Cellar/perl/5.30.3/lib/perl5/5.30.3 /usr/local/lib/perl5/site_perl/5.30.3/darwin-thread-multi-2level /usr/local/lib/perl5/site_perl/5.30.3) at /Users/ohon_ad/Documents/Tools/RepeatModeler/RepeatModeler-2.0.1/RepeatUtil.pm line 78.
BEGIN failed--compilation aborted at /Users/ohon_ad/Documents/Tools/RepeatModeler/RepeatModeler-2.0.1/RepeatUtil.pm line 78.
Compilation failed in require at ./RepeatModeler line 126.
BEGIN failed--compilation aborted at ./RepeatModeler line 126.
```

I used Cpan to install all the dependencies need it by Perl but still having this error when I run RepeatModeler

Can you advice please

**Comment by jebrosen** [comment]
`WUBlastSearchEngine.pm` is part of the `RepeatMasker` dependency, which is missing from `@INC`. The `./configure` program should have asked for a path to the `RepeatMasker` directory, or it can also be hand-edited in `RepModelConfig.pm`.

**Comment by yangkaiyanyangkaiyan** [comment]
i set the path of RMBlast to the RepeatMakser, and i have not configured Wublast, finally this error was still here .  how to handed  edit in RepModelConfig.pm

**Comment by yangkaiyanyangkaiyan** [comment]
Can't locate WUBlastSearchEngine.pm in @INC (you may need to install the WUBlastSearchEngine module) (@INC contains: /home/yangkaiyan/miniconda3/envs/repeat/bin /home/yangkaiyan/miniconda3/envs/repeat/share/RepeatModeler /home/yangkaiyan/miniconda3/envs/repeat/lib/perl5/5.32/site_perl /home/yangkaiyan/miniconda3/envs/repeat/lib/perl5/site_perl /home/yangkaiyan/miniconda3/envs/repeat/lib/perl5/5.32/vendor_perl /home/yangkaiyan/miniconda3/envs/repeat/lib/perl5/vendor_perl /home/yangkaiyan/miniconda3/envs/repeat/lib/perl5/5.32/core_perl /home/yangkaiyan/miniconda3/envs/repeat/lib/perl5/core_perl .) at /home/yangkaiyan/miniconda3/envs/repeat/share/RepeatModeler/RepeatUtil.pm line 78.
BEGIN failed--compilation aborted at /home/yangkaiyan/miniconda3/envs/repeat/share/RepeatModeler/RepeatUtil.pm line 78.
Compilation failed in require at /home/yangkaiyan/miniconda3/envs/repeat/bin/RepeatModeler line 126.
BEGIN failed--compilation aborted at /home/yangkaiyan/miniconda3/envs/repeat/bin/RepeatModeler line 126.

**Comment by BioHlT** [comment]
I ran in to the same error message, Is the issue resolved yet?

**Comment by Carrefour-pirate** [comment]
I met this error too. And, since it says "can't locate XXXX.pm in @INC" , I tried "find ~ -name "XXXX.pm" ". Then, I found there is one in "~/miniconda3/envs/XXX/share/RepeatMasker". So I just simply created a soft link in "~/miniconda3/envs/XXX/share/RepeatModeler", which is contained by "@INC" as it said. But this error rise again with another "XXXXXX.pm", and I did same thing. After several soft links were created, it works. And I finally realized all the "XXXXX.pm" are located in "~/miniconda3/envs/XXX/share/RepeatMasker". 
So maybe it's a better/easier way to directly set "@INC" to contain "~/miniconda3/envs/XXX/share/RepeatMasker".

**Comment by YuzhouGong** [comment]
I have met this error too. My solution is to copy all the .pm files in the ~/xxx/RepeatMasker to the ~/xxx/RepeatModeler.

**Comment by aberaslop** [comment]
@YuzhouGong's solution works perfectly for me. Thank you!

**Comment by YuzhouGong** [comment]
> @YuzhouGong's solution works perfectly for me. Thank you!

Glad to help, mate!
