### ISSUE TITLE
RepeatModeler2.0 bug fix question

### ISSUE THREAD

**Issue by johnssproul** [Dfam-consortium/RepeatModeler#108]
I ran several analyses with RepeatModeler2.0 but I notice that the version history of v2.0.1 references a rare bug related to RepeatScout that was present in 2.0. Does that bug cause a the run to crash? I am wondering if there is an easy way to know if that bug affected my past runs.

**Comment by jebrosen** [comment]
This one?

> RepeatScout in some rare cases will generate models for very long-period satellites.  This can cause Refiner to go crazy creating tons of off-diagonal alignments. This version filters out these rare cases.

If I remember correctly this problem did lead to an out-of-memory error that caused the entire run to fail, so if you had a successful run it's unlikely this bug affected you.

**Comment by johnssproul** [comment]
Yes, that’s the one. Good to know it is likely that bug would have crashed the run. Thanks for the follow up!
