### ISSUE TITLE
LTRStruct bug

### ISSUE THREAD

**Issue by cell-c** [Dfam-consortium/RepeatModeler#113]
Hi,
I encountered a bug about -LTRStruct.

RepeatModeler -database test -pa 20 -LTRStruct
LTRPipeline dependency missing or incorrectly set for NINJA_DIR!   Rerun ./configure or check your command line to ensure that RepeatModeler has access to and the correct version of this dependency.

RepeatModeler  was installed through conda. I independently installed NINJA and add NINJA_DIR in LTRPipeline. And I tried ./configure and failed.
Thank you.

**Comment by jebrosen** [comment]
> RepeatModeler was installed through conda.

I'm a bit concerned about the mixed installation since it will likely be more difficult for either us or the bioconda folks to troubleshoot issues. That said, it's *probably* not the issue here.

>  I independently installed NINJA and add NINJA_DIR in LTRPipeline.

What version of Ninja is reported when you run `/path/to/Ninja -v` separately in a terminal?

> And I tried ./configure and failed.

How did it fail exactly / what error messages? `./configure` is generally easier than editing `RepModelConfig.pm` by hand, since it can detect and explain some common issues with specifying the path.

**Comment by cell-c** [comment]
> > RepeatModeler was installed through conda.
> 
> I'm a bit concerned about the mixed installation since it will likely be more difficult for either us or the bioconda folks to troubleshoot issues. That said, it's _probably_ not the issue here.
> 
> > I independently installed NINJA and add NINJA_DIR in LTRPipeline.
> 
> What version of Ninja is reported when you run `/path/to/Ninja -v` separately in a terminal?
> 
> > And I tried ./configure and failed.
> 
> How did it fail exactly / what error messages? `./configure` is generally easier than editing `RepModelConfig.pm` by hand, since it can detect and explain some common issues with specifying the path.

**Comment by cell-c** [comment]
Thank you!  I have solved this problem. It's caused by that "Ninja" in RepModelConfig.pm did not match "ninja" in Ninja directory.

**Comment by rmhubley** [comment]
FYI:  RepeatModeler is designed to work with a specific version of NINJA.  In the 0.95-cluster version the binary produced by compilation of the source code is named "Ninja" (with mixed capitalization).  Please make sure you are using the correct version.

**Comment by cell-c** [comment]
Thank you! I will adjust to the appropriate version

**Comment by chenHuiRu8** [comment]
> 谢谢！我已经解决了这个问题。这是由于 RepModelConfig.pm 中的“Ninja”与 Ninja 目录中的“ninja”不匹配造成的。

How to solve this problem
