### ISSUE TITLE
Confusion of Results of BuildDatabase

### ISSUE THREAD

**Issue by kuangtianhui** [Dfam-consortium/RepeatModeler#120]
I ran the first step of RepeatModeler, and I got some output file. However, I am not sure that what output files will bet got in this step.
cmd that I used: BuildDatabase -name WY -engine ncbi /public/home/1_WY_annotation/Assembly/Wunmasked.fasta
My output file is below:
WY.nhr
WY.nin
WY.nnd
WY.nni
WY.nog
WY.nsq
WY_RepeatModeler.o14484
WY.translation
Is my results whole？？？

**Comment by jebrosen** [comment]
You should have seen a message like "Number of sequences added to database: ## (### bp)" indicating what was successful - which should match the input fasta file(s). The `WY.n*` files are the output files of `BuildDatabase` which will be used when you run `RepeatModeler`.

**Comment by kuangtianhui** [comment]
I am very happy to recevive your reply. For your reply, I have determined my running results are correct, so I can start working next.
Thanks again
