### ISSUE TITLE
Unknown option: ltrstruct

### ISSUE THREAD

**Issue by ld9866** [Dfam-consortium/RepeatModeler#142]
Hello, I used conda to install the related software, but when l gave me the following command, an error would be reported. But when I delete the ltrstruct, it can run normally. What should I do?
Good luck！

RepeatModeler -database pig -pa 40 -LTRStruct
Unknown option: ltrstruct
SYNOPSIS
      RepeatModeler [-options] -database <XDF Database>

DESCRIPTION
    The options are:

**Comment by jebrosen** [comment]
> RepeatModeler -database pig -pa 40 -LTRStruct
> Unknown option: ltrstruct

This command line and error message do not match. Did you happen to type it in lowercase (`-ltrstruct`) instead when you got that error message?

> Hello, I used conda to install the related software

There is another problem with this option: bioconda does not currently include NINJA, one of the requirements for using `-LTRStruct`. There are a few options:

* Install NINJA, and then run `configure` in your RepeatModeler installation to set up that path
* Install RepeatModeler, NINJA, and other required software all manually (not with bioconda)
* Try the [Dfam TE Tools container](https://github.com/Dfam-consortium/TETools/) or another container-based approach. The latest version of that container does include NINJA and the other required software for `-LTRStruct`.

**Comment by ld9866** [comment]
The latest version of that container does include NINJA and the other required software for -LTRStruct.
Thank you very much for your help. Through the third method you provided, I can now operate normally. It's a great operation.

**Comment by jebrosen** [comment]
Glad to hear that helped!

**Comment by Midreancgle** [comment]
Hello,I have the same question.when I run `RepeatModeler -database Mo -engine ncbi -pa 20 -LTRStruct >& run.out &`,the run.out show 
` LTRPipeline dependency missing or incorrectly set for NINJA_DIR!
   Rerun ./configure or check your command line to ensure that RepeatModeler
  has access to and the correct version of this dependency.`
I used conda to install the NINJA and LtrDeteector, and set up the path to the RepeatModeler and LTRPipeline.I test all the dependent software, LtrDetector、LTR_retriever、MAFFT、CD-HIT、NINJA、LTRHarvest.They all can output the help pages.

`#!/bin/bash
  
REPEATMODELER_DIR=/home/yue/anaconda3/envs/python27/share/RepeatModeler
REPEATMASKER_DIR=/home/yue/anaconda3/envs/python27/share/RepeatMasker
ABBLAST_DIR=/home/yue/anaconda3/envs/python27/bin
CDHIT_DIR=/home/yue/anaconda3/envs/python27/bin
GENOMETOOLS_DIR=/home/yue/anaconda3/envs/python27/bin
LTR_RETRIEVER_DIR=/home/yue/anaconda3/envs/python27/bin
MAFFT_DIR=/home/yue/anaconda3/envs/python27/bin
NINJA_DIR=/home/yue/anaconda3/envs/python27/bin/
RECON_DIR=/home/yue/anaconda3/envs/python27/bin
RMBLAST_DIR=/home/yue/anaconda3/envs/python27/bin
RSCOUT_DIR=/home/yue/anaconda3/envs/python27/bin
TRF_PRGM=/home/yue/anaconda3/envs/python27/bin/trf
LTR_DETECTOR_DIR=/home/yue/anaconda3/pkgs/LtrDetector-master/bin
export REPEATMODELER_DIR REPEATMASKER_DIR ABBLAST_DIR TRFMASK_DIR CDHIT_DIR GENOMETOOLS_DIR LTR_RETRIEVER_DIR MAFFT_DIR NINJA_DIR RECON_DIR RMBLAST_DIR RSCOUT_DIR TRF_PRGM LTR_DETECTOR_DIR
NAME=$(basename $0)
perl /home/yue/anaconda3/envs/python27/share/RepeatModeler/${NAME} $@
~                                                                                                                                                                                                                                                  
"RepeatModeler"`
Could you give me some help ?Thanks

**Comment by jebrosen** [comment]
@Midreancgle

> I used conda to install the NINJA

To my knowledge, conda/bioconda still does not have a package for NINJA and it needs to be installed and configured separately when installed that way. (the latest version is at: https://github.com/TravisWheelerLab/NINJA/releases/tag/0.98-cluster_only ) . Which conda package for NINJA are you referring to?

**Comment by Midreancgle** [comment]
Thank you for your help！
I installed version ninja=1.10 by conda before. After seeing your reply, I installed ninja manually and solved the problem about LTRPipeline.
But now there is a problem.The same fastq file, the same commands, but the results of multiple runs are different.Can you tell me why this phenomenon occurs?

`BuildDatabase -name Mo -engine ncbi genome.fa
nohup RepeatModeler -database Mo -engine ncbi -pa 20 -LTRStruct >& run.out &
RepeatMasker -lib Mo-families.fa -e ncbi -pa 30 -gff genome.fa`

==================================================
file name: genome.fa                
sequences:             1
total length:    7978604 bp  (7969204 bp excl N/X-runs)
GC level:         51.23 %
bases masked:    1196896 bp ( 15.00 %)
==================================================
             
--------------------------------------------------
Retroelements          604       740227 bp    9.28 %
  
   LTR elements:       586       692279 bp    8.68 %
  
DNA transposons        134       173197 bp    2.17 %

Rolling-circles          0            0 bp    0.00 %

Unclassified:          185       196158 bp    2.46 %

Total interspersed repeats:     1109582 bp   13.91 %


Small RNA:               0            0 bp    0.00 %

Satellites:              0            0 bp    0.00 %
Simple repeats:       2064        75606 bp    0.95 %
Low complexity:        269        11708 bp    0.15 %
==================================================

==================================================
file name: genome.fa                
sequences:             1
total length:    7978604 bp  (7969204 bp excl N/X-runs)
GC level:         51.23 %
bases masked:    1193354 bp ( 14.96 %)
==================================================
           
--------------------------------------------------
Retroelements          659       877753 bp   11.00 %
   
   LTR elements:       599       683874 bp    8.57 %
     

DNA transposons         92       117452 bp    1.47 %
   
Rolling-circles          0            0 bp    0.00 %

Unclassified:          215       111266 bp    1.39 %

Total interspersed repeats:     1106471 bp   13.87 %


Small RNA:               0            0 bp    0.00 %

Satellites:              0            0 bp    0.00 %
Simple repeats:       2056        75175 bp    0.94 %
Low complexity:        269        11708 bp    0.15 %
==================================================

**Comment by jebrosen** [comment]
Hi @Midreancgle, I have tried to send a response to this question by email. Here is the message again; I hope this helps to answer:

---

I am glad to hear your first problem is solved.

The difference in output looks normal; see also https://github.com/Dfam-consortium/RepeatModeler/issues/11. RepeatModeler takes samples of the genome, and not every run is perfectly identical by default. In order to reproduce a specific run of RepeatModeler, the "Random Number Seed" from the program output can be used with the "-srand" option for RepeatModeler.
