### ISSUE TITLE
Adding paths to dependency directories during set up

### ISSUE THREAD

**Issue by jaredbernard** [Dfam-consortium/RepeatModeler#147]
Just a quick question about setting up RepeatModeler. I've been going through the prompts for adding pathways to dependencies during installation, and I haven't had any problem with any except `LTR_retriever`. I followed the installation of that package found [here](https://github.com/oushujun/LTR_retriever), and it automatically installed in `/home/me/miniconda3/envs/LTR_retriever/` rather than `/usr/local/` like most of the others. When I add the path, RepeatModeler gives me an error:

```
Could not find the required program "LTR_retriever" inside
the directory "/home/me/miniconda3/envs/LTR_retriever/"!
```

Any ideas of why this would be? Would it help to edit "RepModelConfig.pm" directly?

**Comment by jebrosen** [comment]
I don't think I have used a conda env to install `LTR_retriever` in this way, but I expect there are subdirectories in `/home/me/miniconda3/envs/LTR_retriever/` such as `bin` or `share`, where the `LTR_retriever` program is actually located. `RepeatModeler` tries to guess some of these subdirectories, but it may need more help in this case.

You could also use a command such as this one to find the program, wherever it happens to be:

`find /home/me/miniconda3/envs/LTR_retriever/ -type f -name LTR_retriever`

**Comment by jaredbernard** [comment]
Thanks, @jebrosen. I tried adding `bin` or `lib` at the end, but I get the same error. Maybe I need to find a different way to install `LTR_retriever`.

**Comment by jaredbernard** [comment]
@jebrosen, when you indicated that you installed `LTR_retriever` by a different method than conda (the only method shown on [the repo](https://github.com/oushujun/LTR_retriever)), I tried the following alternative method:
```
wget https://github.com/oushujun/LTR_retriever/archive/v2.8.tar.gz &&  mv v2.8.tar.gz LTR_retriever-2.8.tar.gz &&  tar -C /usr/local -xzvf LTR_retriever-2.8.tar.gz && rm LTR_retriever-2.8.tar.gz
```
And it worked; now RepeatModeler is ready to go! Thanks! :^)

**Comment by jebrosen** [comment]
Great to hear it! Please do reply here or post a new issue if you have further questions.
