### ISSUE TITLE
Configuring 

### ISSUE THREAD

**Issue by SheepwormJM** [Dfam-consortium/RepeatModeler#157]
Hi,

I'm just trying to finish configuring RepeatModeler on a computer cluster. 

It's asking for the UCSCTOOLS directory but I can't find anything in the installation instructions about this. Is this what I'm looking for: https://anaconda.org/mvdbeek/ucsc_tools ? 

Thanks!
Jenni

**Comment by jebrosen** [comment]
> It's asking for the UCSCTOOLS directory but I can't find anything in the installation instructions about this.

It looks like that information is indeed missing! We should definitely update those instructions.


The UCSC tools refers to these command-line tools distributed as binaries and as source code by the UCSC Genome Browser: <https://hgdownload.soe.ucsc.edu/downloads.html#utilities_downloads>. I don't know if that particular package you found includes the tools currently required by RepeatModeler; in case it does not, here are some other packages available through bioconda that should also work (and happen to be more recently updated as well):

https://anaconda.org/bioconda/ucsc-fatotwobit
https://anaconda.org/bioconda/ucsc-twobitinfo
https://anaconda.org/bioconda/ucsc-twobittofa

**Comment by SheepwormJM** [comment]
Thanks @jebrosen! I will give these a try. :)
