### ISSUE TITLE
FastaDB::compact - Error could not locate file /group/pasture/Saila/scanPAV/Kyuss_Imp04_40kb/RepeatMasker_imp04vsKyuss/RM_122929.FriMay61008492022/round-1/sampleDB-1.fa!

### ISSUE THREAD

**Issue by biowackysci** [Dfam-consortium/RepeatModeler#169]
**Hello Team,

I am relatively new to repeatModeler,

I am trying to use RepeatModeler on a database that is made up of presence and absence variants in two genomes. 
I use the following 
RepeatModeler -database /group/pasture/Saila/scanPAV/Kyuss_Imp04_40kb/pavs_present_in_Imp04_40kb_2kbabovepavs.fasta
 to run the job.
I get an error 
"FastaDB::compact - Error could not locate file /group/pasture/Saila/scanPAV/Kyuss_Imp04_40kb/RepeatMasker_imp04vsKyuss/RM_86770.FriMay61004432022/round-1/sampleDB-1.fa!
 at /usr/local/eb/software/generic/RepeatModeler/2.0.1-intel-2019a-Perl-5.28.1/RepeatModeler line 837. "

Looks like the error  appears 1000 times with my input file - I think that error is more pertinent to the problem. I think that the code is trying to process the input file, hitting an error lots of times (hence all those lines beginning with 'Error:' ) and failing to build up the .fa file. Once it finishes the first stage, it then tries to read the .fa file and finds it empty, and at that point it throws the error 

Can someone please help me to go about it?

Thanks

**Comment by rmhubley** [comment]
Sorry for the late response.  I believe this issue has been resolve, however if you are still experiencing this problem with recent versions of RepeatModeler please let us know.
