### ISSUE TITLE
sumarry result tabel 

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [Dfam-consortium/RepeatModeler#172]
I have run repeatmodeler succesfully but i didn't get this type of summary table. 
this repeatmodeler table i got from gensas webtool repeatmodeler
can you guide me where i can find this table if i use repeatmodeler. by cmd.?
i have checked round-1 to round-4

file name: t_627da85946ceb.fna      
sequences:             1
total length:   29372977 bp  (29372977 bp excl N/X-runs)
GC level:         44.07 %
bases masked:   11277996 bp ( 38.40 %)

               number of      length   percentage
               elements*    occupied  of sequence

Retroelements         3957      5684421 bp   19.35 %
   SINEs:                0            0 bp    0.00 %
   Penelope              0            0 bp    0.00 %
   LINEs:              326       105797 bp    0.36 %
    CRE/SLACS            0            0 bp    0.00 %
     L2/CR1/Rex          0            0 bp    0.00 %
     R1/LOA/Jockey       0            0 bp    0.00 %
     R2/R4/NeSL          0            0 bp    0.00 %
     RTE/Bov-B           0            0 bp    0.00 %
     L1/CIN4           326       105797 bp    0.36 %
   LTR elements:      3631      5578624 bp   18.99 %
     BEL/Pao             0            0 bp    0.00 %
     Ty1/Copia         225       245581 bp    0.84 %
     Gypsy/DIRS1      3167      5256837 bp   17.90 %

**Comment by rmhubley** [comment]
RepeatModeler is a library generating tool and not an annotation tool.  You could use your generated library with RepeatMasker to obtain these types of statistics.
