### ISSUE TITLE
Is ARM64 a supported platform ?

### ISSUE THREAD

**Issue by gancho-ivanov** [Dfam-consortium/RepeatModeler#175]
**What do you want to know?**

I'd like to ask whether RepeatModeler could be used on Linux/MacOS ARM64 machines ?

I wanted to use it via the Docker image but it seems it is only for linux/amd64, so I created https://github.com/Dfam-consortium/TETools/issues/25.

Are you aware of any other issues related to the CPU architecture ?

Thank you!

**Comment by rmhubley** [comment]
Not yet.  But I just finished work on RMBlast 2.13.0 and I have provided a M1 natively compiled version of the tool (experimental).  I am also very close to releasing a new RepeatMasker/RepeatModeler that takes advantage of the query-based threading feature of this new RMBlast release (couple of weeks away).

**Comment by rmhubley** [comment]
Release has been out for awhile, closing this request.
