### ISSUE TITLE
RepModelConfig.pm need to account for more binaries

### ISSUE THREAD

**Issue by EricDeveaud** [Dfam-consortium/RepeatModeler#177]
hello, 
some programs are not dicumented in RepModelConfig.pm
eg `imagespread`, `edgeredef`,  and `famdef` are not documented in `RECON_DIR` section of config file hile they are used in RepeatModeler currently  only `eledef` and `eleredef` are "checked"

same applies to `filter-stage-1.prl` for `RSCOUT_DIR` that only contains `build_lmer_table` and `RepeatScout`
same for `blastx` missing the `RMBLAST_DIR` while used in `RepeatClassifier` 

regards

Eric

**Comment by rmhubley** [comment]
Software dependencies are configured by project.  The RECON package includes all of the binaries you listed and are expected to be in the folder pointed to by the RepeatModeler configuration file.  The same is true for RepeatScout. If you are referring to the 'expected_binaries' section of the config file, those list contain only a minimal set for sanity checking and haven't been expanded to include all possible files contained in a dependencies distribution.
