### ISSUE TITLE
Can't call method "setLeftLinkedHit"

### ISSUE THREAD

**Issue by Ghanizadeh1980** [Dfam-consortium/RepeatModeler#179]
Hi,

Can somebody help me with the error message below, please? I was running RepeatMasker, and everything was running smoothly for about 2 hours, then suddenly, this message popped up. Here is the command."sudo docker run -it --rm -v`pwd`:`pwd` dfam/tetools:latest RepeatMasker /home/dieter/GB/medaka/consensus.fasta -lib /home/dieter/GB/repeatmodeller/GB-families.fa -pa 8 -gff -dir /home/dieter/GB/repeatmasker/"

"Can't call method "setLeftLinkedHit" on an undefined value at /opt/RepeatMasker/ProcessRepeats line 3726."

Regards,

Hossein.

**Comment by rmhubley** [comment]
Please try the latest version of RepeatMasker 4.1.3p1 which should fix this issue.
