### ISSUE TITLE
A way to speed up Repeatmodeler

### ISSUE THREAD

**Issue by yangfangyuan0102** [Dfam-consortium/RepeatModeler#184]
For users with enough memory, maybe we can improve the running speed by mounting RAM as a virtual disk, or directly run repeatmodeler in the tmpfs filesystem (the RAM) directory (e.g. "/dev/shm" in most Linux). Use commond df to show the existing tmpfs directory, or mount a new "tmpfs" directory using: sudo mount - t tmpfs - o size=20g tmpfs ./work_dir
Shutdown or umount will cause file loss. Remember to copy the file out when finished. 

Best
Fangyuan Yang

**Comment by rmhubley** [comment]
RepeatModeler runtimes are improved by faster I/O rates (local HDs, SSDs, RAM disks etc).  This is a good suggestion for those with enough RAM on their machine.
