### ISSUE TITLE
Linup error: "I don't know how to parse this id"

### ISSUE THREAD

**Issue by francicco** [Dfam-consortium/RepeatModeler#193]
Hi,

I'm getting `I don't know how to parse this id: CONSENSUS-tAlp-rnd-1_family-0` while executing `Linup`.
I don't get why.
Any help?
Thanks a lot
Francesco

**Comment by rmhubley** [comment]
I am sorry we didn't get to this request in a timely fashion but I do have an answer should it help others.  This error message is printed in Linup when you are using the "-includeFlanking" option.  This option uses the sequence identifier and coordinates (encoded in the MSA ID field as seqID:start-end_orient) to determine the coordinates for obtaining the flanking sequences.  "CONSENSUS-tAlp-rnd-1_family-0" is not a sequence in your assembly and therefore could not be used.  Perhaps we should have an option to ignore sequences that cannot be looked up.  Although we typically do not recommend including an artificial sequences (e.g consensus) in a MSA as it pollutes the statistics of the MSA and causes drift on the MSA derived consensus.
