### ISSUE TITLE
How do I get genome.fa.pass.list(LTR_retriever output file) ?

### ISSUE THREAD

**Issue by th2ch-g** [Dfam-consortium/RepeatModeler#196]
**What do you want to know?**
I want to know how to get genome.fa.pass.list file(This is LTR_retriever output file [here](https://github.com/oushujun/LTR_retriever)).
I run RepeatModeler with -LTRStruct option.

**Comment by rmhubley** [comment]
Sorry we didn't get this issue in a timely fashion.  This file is saved to the temporary working directory and deleted upon successful completion.  If there is a particular piece of information you would like exposed in the RepeatModeler output please let us know and we can work this into a future version.
