### ISSUE TITLE
0 families discovered

### ISSUE THREAD

**Issue by nicolasalexandre21** [Dfam-consortium/RepeatModeler#197]
Hello, I installed the most recent RepeatModeler 2.0.4 from source and it seems to be running smoothly through each round such that the output directories are full of fasta files. However, at the end of each step in the log file as you'll see below, it keeps saying 0 families discovered. Is this something I can ignore until the rounds finish or does this mean there is something wrong?

RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
   - Final Sample Size = 40028157 bp ( 40027857 non ambiguous )
   - Num Contigs Represented = 43
   - Sequence extraction : 00:04:15 (hh:mm:ss) Elapsed Time
 -- Running RepeatScout on the sequences...
   - RepeatScout: 00:12:20 (hh:mm:ss) Elapsed Time
Round Time: 00:21:03 (hh:mm:ss) Elapsed Time : 0 families discovered.

RepeatModeler Round # 2
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 10000000 bp
   - Sequence extraction : 00:01:08 (hh:mm:ss) Elapsed Time
 -- Running TRFMask on the sequence...
   - TRFMask time 00:00:26 (hh:mm:ss) Elapsed Time
 -- Sample Stats:
       Sample Size 10004948 bp
       Num Contigs Represented = 26
       Non ambiguous bp:
             Initial: 10004848 bp
             After Masking: 9884687 bp
             Masked: 1.20 % 
 -- Input Database Coverage: 10004948 bp out of 2501084987 bp ( 0.40 % )
Sampling Time: 00:01:36 (hh:mm:ss) Elapsed Time
Running all-by-other comparisons...
  - Total Comparisons = 31375
Comparison Time: 01:06:52 (hh:mm:ss) Elapsed Time, 10510239 HSPs Collected
Number of families returned by RECON: 4340
Round Time: 04:02:58 (hh:mm:ss) Elapsed Time : 0 families discovered.

**Comment by rmhubley** [comment]
I'm afraid we didn't get to this question in a timely fashion.  Please let me know if you are still having an issue and I would be happy to help.
