### ISSUE TITLE
Job directory RM_.* cannot be automatically deleted  after the run ends

### ISSUE THREAD

**Issue by bitahu** [Dfam-consortium/RepeatModeler#204]
**What do you want to know?**

the job directory RM_.* cannot be automatically deleted after the run ends , is there a problem?

**Helpful context**

RepeatModeler Version 2.0.4
===========================
Using output directory = /home/hang/work/data1/fit2/repeat/RM_880020.TueApr181154022023
Search Engine = rmblast 2.13.0+
Dependencies: TRF 4.09, RECON , RepeatScout 1.0.5, RepeatMasker 4.1.4
LTR Structural Analysis: Disabled [use -LTRStruct to enable]
Random Number Seed: 1681790039
Database = /home/hang/work/data1/fit2/repeat/diatom .
  - Sequences = 64
  - Bases = 32437365
Storage Throughput = excellent ( 1570.51 MB/s )

Ready to start the sampling process.
INFO: The runtime of RepeatModeler heavily depends on the quality of the assembly
      and the repetitive content of the sequences.  It is not imperative
      that RepeatModeler completes all rounds in order to obtain useful
      results.  At the completion of each round, the files ( consensi.fa, and
      families.stk ) found in:
      /home/hang/work/data1/fit2/repeat/RM_880020.TueApr181154022023/ 
      will contain all results produced thus far. These files may be 
      manually copied and run through RepeatClassifier should the program
      be terminated early.

RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
   - Final Sample Size = 32437276 bp ( 32272534 non ambiguous )
   - Num Contigs Represented = 64
   - Sequence extraction : 00:00:03 (hh:mm:ss) Elapsed Time
 -- Running RepeatScout on the sequences...
   - RepeatScout: Running build_lmer_table ( l = 14 )..
   - RepeatScout: Running RepeatScout.. : 752 raw families identified
   - RepeatScout: Running filtering stage.. 0 families remaining
   - RepeatScout: 00:07:04 (hh:mm:ss) Elapsed Time
NOTE: RepeatScout did not return any models.
Round Time: 00:07:07 (hh:mm:ss) Elapsed Time : 0 families discovered.

RepeatModeler Round # 2
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 10000000 bp
   - Sequence extraction : 00:00:02 (hh:mm:ss) Elapsed Time
 -- Running TRFMask on the sequence...
       252 Tandem Repeats Masked
   - TRFMask time 00:00:09 (hh:mm:ss) Elapsed Time
 -- Sample Stats:
       Sample Size 10054906 bp
       Num Contigs Represented = 40
       Non ambiguous bp:
             Initial: 10013248 bp
             After Masking: 9963694 bp
             Masked: 0.49 % 
 -- Input Database Coverage: 10054906 bp out of 32437365 bp ( 31.00 % )
Sampling Time: 00:00:14 (hh:mm:ss) Elapsed Time
Running all-by-other comparisons...
  - Total Comparisons = 34453
        0% completed,  00:39:09 (hh:mm:ss) est. time remaining.
        1% completed,  00:38:55 (hh:mm:ss) est. time remaining.
        2% completed,  00:35:50 (hh:mm:ss) est. time remaining.
        ......
       99% completed,  00:0:00 (hh:mm:ss) est. time remaining.
      100% completed,  00:0:00 (hh:mm:ss) est. time remaining.
Comparison Time: 00:51:15 (hh:mm:ss) Elapsed Time, 5489 HSPs Collected
  - RECON: Running imagespread..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - RECON: Running initial definition of elements ( eledef )..
RECON Elapsed: 00:00:01 (hh:mm:ss) Elapsed Time
  - RECON: Running re-definition of elements ( eleredef )..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - RECON: Running re-definition of edges ( edgeredef )..
RECON Elapsed: 00:00:02 (hh:mm:ss) Elapsed Time
  - RECON: Running family definition ( famdef )..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - Obtaining element sequences
Number of families returned by RECON: 1146
Processing families with greater than 15 elements
Instance Gathering: 00:00:00 (hh:mm:ss) Elapsed Time
About to run 5 refinement jobs
Refinement: 00:02:06 (hh:mm:ss) Elapsed Time
Family Refinement: 00:02:06 (hh:mm:ss) Elapsed Time
Round Time: 00:53:38 (hh:mm:ss) Elapsed Time : 5 families discovered.

RepeatModeler Round # 3
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 30000000 bp
   - Sequence extraction : 00:00:03 (hh:mm:ss) Elapsed Time
 -- Running TRFMask on the sequence...
       573 Tandem Repeats Masked
   - TRFMask time 00:00:20 (hh:mm:ss) Elapsed Time
 -- Masking repeats from the previous rounds...
    -- Collecting 376 ranges...
       370 repeats masked totaling 92551 bp(s).
   - TE Masking time 00:00:18 (hh:mm:ss) Elapsed Time
 -- Sample Stats:
       Sample Size 22382290 bp
       Num Contigs Represented = 57
       Non ambiguous bp:
             Initial: 22259206 bp
             After Masking: 22046270 bp
             Masked: 0.96 % 
 -- Input Database Coverage: 32437196 bp out of 32437365 bp ( 100.00 % )
Sampling Time: 00:00:46 (hh:mm:ss) Elapsed Time
Running all-by-other comparisons...
  - Total Comparisons = 170820
        0% completed,  03:4:37 (hh:mm:ss) est. time remaining.
        1% completed,  02:21:46 (hh:mm:ss) est. time remaining.
        ......
       99% completed,  00:0:00 (hh:mm:ss) est. time remaining.
      100% completed,  00:0:00 (hh:mm:ss) est. time remaining.
Comparison Time: 03:02:11 (hh:mm:ss) Elapsed Time, 28191 HSPs Collected
  - RECON: Running imagespread..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - RECON: Running initial definition of elements ( eledef )..
RECON Elapsed: 00:00:01 (hh:mm:ss) Elapsed Time
  - RECON: Running re-definition of elements ( eleredef )..
RECON Elapsed: 00:00:02 (hh:mm:ss) Elapsed Time
  - RECON: Running re-definition of edges ( edgeredef )..
RECON Elapsed: 00:00:11 (hh:mm:ss) Elapsed Time
  - RECON: Running family definition ( famdef )..
RECON Elapsed: 00:00:00 (hh:mm:ss) Elapsed Time
  - Obtaining element sequences
Number of families returned by RECON: 3375
Processing families with greater than 15 elements
Instance Gathering: 00:00:00 (hh:mm:ss) Elapsed Time
About to run 17 refinement jobs
Refinement: 00:08:06 (hh:mm:ss) Elapsed Time
Family Refinement: 00:08:06 (hh:mm:ss) Elapsed Time
Round Time: 03:11:18 (hh:mm:ss) Elapsed Time : 14 families discovered.

RepeatScout/RECON discovery complete: 19 families found

RepeatClassifier Version 2.0.4
======================================
  - Looking for Simple and Low Complexity sequences..
  - Looking for similarity to known repeat proteins..
  - Looking for similarity to known repeat consensi..
Classification Time: 00:06:55 (hh:mm:ss) Elapsed Time

Program Time: 04:18:58 (hh:mm:ss) Elapsed Time
Working directory:  /home/hang/work/data1/fit2/repeat/RM_880020.TueApr181154022023
may be deleted unless there were problems with the run.

The results have been saved to:
  /home/hang/work/data1/fit2/repeat/diatom-families.fa  - Consensus sequences for each family identified.
  /home/hang/work/data1/fit2/repeat/diatom-families.stk - Seed alignments for each family identified.
  /home/hang/work/data1/fit2/repeat/diatom-rmod.log     - Execution log.  Useful for reproducing results.

The RepeatModeler stockholm file is formatted so that it can
easily be submitted to the Dfam database.  Please consider contributing
curated families to this open database and be a part of this growing
community resource.  For more information contact help@dfam.org.

**Comment by rmhubley** [comment]
I am not sure what the issue is.  Are you unable to delete the directory after the program has completed?  Did you get an error message from RepeatModeler itself indicating that it tried and failed to remove a directory?
