### ISSUE TITLE
the lastest version of repeatmodeler was error when running it,  reveals "ERROR from search engine (3) "

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [Dfam-consortium/RepeatModeler#205]
RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
   - Final Sample Size = 40003535 bp ( 40003535 non ambiguous )
   - Num Contigs Represented = 10
   - Sequence extraction : 00:00:32 (hh:mm:ss) Elapsed Time
 -- Running RepeatScout on the sequences...
   - RepeatScout: Running build_lmer_table ( l = 14 )..
   - RepeatScout: Running RepeatScout.. : 1444 raw families identified
   - RepeatScout: Running filtering stage.. 1255 families remaining
   - RepeatScout: 00:14:49 (hh:mm:ss) Elapsed Time
: 0 found in 00:00:01 (hh:mm:ss) Elapsed Time
   - Collecting repeat instances...Round Time: 00:15:24 (hh:mm:ss) Elapsed Time : 0 families discovered.

RepeatModeler Round # 2
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 10000000 bp
   - Sequence extraction : 00:00:09 (hh:mm:ss) Elapsed Time
 -- Running TRFMask on the sequence...
       804 Tandem Repeats Masked
   - TRFMask time 00:00:44 (hh:mm:ss) Elapsed Time
 -- Sample Stats:
       Sample Size 10000454 bp
       Num Contigs Represented = 10
       Non ambiguous bp:
             Initial: 10000454 bp
             After Masking: 9578375 bp
             Masked: 4.22 % 
 -- Input Database Coverage: 10000454 bp out of 749771133 bp ( 1.33 % )
Sampling Time: 00:00:54 (hh:mm:ss) Elapsed Time
Running all-by-other comparisons...
  - Total Comparisons = 31125
WARNING: Retrying batch ( 1 ) [ 3 ]...
WARNING: Retrying batch ( 1 ) [ 3 ]...

> **FATAL ERROR: RepeatModeler giving up. One or more**

batches failed!  Unfortunately this type of error
cannot be recovered from. Please submit the following
details to the feedback page at the repeatmasker
website:

       http://www.repeatmasker.org

RepeatModeler Version: 2.0.4
Search Engine: rmblast [ 2.13.0+ ]
Command Line: /public/home/zhangjiangjiang/software/RepeatModeler-2.0.4/RepeatModeler-database repeat_hap1 -threads 5 -LTRStruct
Batch Number: 1
Disk Space:
Filesystem                     1K-blocks          Used     Available Use% Mounted on
ParaStor300S_ParaStor300S 11128852512768 8931361878836 2197490633932  81% /public

System Memory:
Further details about this problem may be found in
the directory: /public/home/zhangjiangjiang/jjzhang/yan/genome/hemp/changsha/03.fusion/modif/repeat/RM_94657.MonMay12044552023

and the error information was 
ERROR from search engine (3) 

ERROR from search engine (3) 

ERROR from search engine (3) 

ERROR from search engine (3) 

ERROR from search engine (3)

**Comment by ywddwed** [comment]
Hi! I encountered the same error when running RepeatModeler. I want to know if you have solved this problem and how? Thanks!

**Comment by Jiangjiangzhang6** [comment]
I re-installed the software and the error was solution, and sometimes the conda environment would conflict with the software


| |
张江江
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 5/28/2023 21:37 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Dfam-consortium/RepeatModeler] the lastest version of repeatmodeler was error when running it, reveals "ERROR from search engine (3) " (Issue #205) |

Hi! I encountered the same error when running RepeatModeler. I want to know if you have solved this problem and how? Thanks!

**Comment by rmhubley** [comment]
Is this still a problem for you?

**Comment by Jiangjiangzhang6** [comment]
its ok, it had solved.
thank you for your responsing


| |
张江江
|
|
***@***.***
|
---- Replied Message ----
| From | Robert ***@***.***> |
| Date | 6/10/2023 03:51 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Dfam-consortium/RepeatModeler] the lastest version of repeatmodeler was error when running it, reveals "ERROR from search engine (3) " (Issue #205) |

Is this still a problem for you?
