### ISSUE TITLE
LTR Harvest - core dumped

### ISSUE THREAD

**Issue by pedro-mmartins** [Dfam-consortium/RepeatModeler#206]
My colleagues and I are working on the annotation of new genomes we just sequenced. We are using RepeatModeler within the Docker container `docker run -it --rm dfam/tetools:latest`, with the following command line: `RepeatModeler -database [database] -threads 30 -LTRStruct  >log 2>err`. But when we get to the LTR Structural Analysis we always get the following error: 

```
LtrPipeline: GenomeTools failed to run ltrharvest. Error code: 139
LtrPipeline: Ltrharvest returned an unexpected result line: 
Segmentation fault (core dumped)
```

Here's what comes up in the log file:
```
LTR Structural Analysis
=======================
Running LtrHarvest...LTRPipeline: No results returned from LTR structural finder ( LtrHarvest ).
LTRPipeline Time: 40:58:15 (hh:mm:ss) Elapsed Time
```
The database for each genome was prepared with the same command line: `BuildDatabase -name [database] [genome.fasta]`.

This has happend with some genomes, but not with other ones, and it doesn't seem to be related to genome size. 

Has anyone had the same problem using the Docker container? How can we solve it?

Thanks!

**Comment by rmhubley** [comment]
I am not sure this is a Docker issue, but rather a LtrHarvest issue.  Have you tried running LtrHarvest by hand on these genomes?
