### ISSUE TITLE
RepeatScout did not return any models & ERROR from search engine 

### ISSUE THREAD

**Issue by ywddwed** [Dfam-consortium/RepeatModeler#208]
Hi! I had some problems running repeatmodeler with the following command line: nohup RepeatModeler -database lin -pa 10 >run.log 
&. In the round1, it showed that: NOTE: RepeatScout did not return any models. And from round2, it errors with ERROR from search engine (127). 
[run.log](https://github.com/Dfam-consortium/RepeatModeler/files/11584379/run.log)

Below is the version of the packages installed in repeatmodeler environment:
![image](https://github.com/Dfam-consortium/RepeatModeler/assets/106568672/4b0dba80-6f4c-41a6-b209-67aef63fe7db)

May I ask what causes this? What should I do about it? Thanks!

**Comment by rmhubley** [comment]
Woah...that's a very old version of RepeatModeler (1.0.8).  Do you need to use that version?  We are at 2.0.4 now.
