### ISSUE TITLE
Can't locate TRF.pm in @INC

### ISSUE THREAD

**Issue by aberaslop** [Dfam-consortium/RepeatModeler#22]
Hi!
I am trying to run RepeatModeler and RepeatMasker. During configuration, neither of them complain about where to find trf (I assume they are finding it). When I run: 
 nohup RepeatModeler-open-1.0.11/RepeatModeler -engine ncbi -pa 3 -database Fungus >&run.out&, 

and look at the run.out file, run1 seems not to complain, and then run2 and the following ones say: 

RepeatModeler Round # 2
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 3000000 bp
 -- Running TRFMask on the sequence...
Can't locate TRF.pm in @INC (you may need to install the TRF module) (@INC contains: /home/manager/Documents/maker/exe/RepeatMasker /home/manager/Documents/maker/exe/RepeatModeler-open-1.0.11 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/manager/Documents/maker/exe/RepeatModeler-open-1.0.11/TRFMask line 85.
BEGIN failed--compilation aborted at /home/manager/Documents/maker/exe/RepeatModeler-open-1.0.11/TRFMask line 85.

The end of the file looks like this:

Discovery complete: 28 families found
Classifying Repeats...
RepeatClassifier Version open-1.0.11
===============================
Search Engine = ncbi
  - Looking for Simple and Low Complexity sequences..
Something went wrong with the TRFMask program.  The tmpConsensi.fa.masked file was missing or empty!
Classification Time: 00:00:00 (hh:mm:ss) Elapsed Time
Program Time: 00:58:38 (hh:mm:ss) Elapsed Time
Working directory:  /home/manager/Documents/maker/exe/RM_16622.TueMar51738352019
may be deleted unless there were problems with the run.

The results have been saved to:
Fungus-families.fa  - Consensus sequences for each family identified.
Fungus-families.stk - Seed alignments for each family identified.

This version of RepeatModeler can upload families directly to the
open repeat database - Dfam_consensus.  Please consider uploading your final
curated library using the RepeatModeler "util/dfamConsensusTool.pl" script
( details at http://www.repeatmasker.org/RepeatModeler/dfamConsensusTool ) or
posting your raw (uncurated) RepeatModeler results to the TE Raw Dataset
Repository ( http://www.repeatmasker.org/Dfam_consensus/#/public/repository ).

Does anyone know what this means? 

Thank you!

**Comment by pig-raffles** [comment]
Did you change the name of the executable to just "trf"?

**Comment by aberaslop** [comment]
Hi! Thank you for your answer.
Yes, I did. I also made it executable (I think) by typing chmod a+x trf. Do you think this could be it?

**Comment by pig-raffles** [comment]
Hi,

I am very far from being any sort of expert on computing. I just had a lot
of problems getting RepeatModeler to install and run, I managed it but it
was a while ago and have forgotten a lot.

I think I used "chmod 775 trf" but am unsure how equivalent it is to your
command. Have you checked that the path to the trf executable you provided
 is correct when setting up RepeatModeler?

**Comment by aberaslop** [comment]
Hi again,

thank you for your time. I downloaded trf again and made it executable with "chmod 775 trf", just in case. It did not solve the problem. I think the path to the executable is correct because the ./configure step does not complain. I have also tried different locations and different iterations of the path, but nothing has worked. I currently have it stored in: 
/home/manager/Documents/maker/exe/RepeatMasker

I have tried the path in all these iterations:
/home/manager/Documents/maker/exe/RepeatMasker
/home/manager/Documents/maker/exe/RepeatMasker/
/home/manager/Documents/maker/exe/RepeatMasker/trf

nothing works. Any other idea would be much appreciated.

Thanks!

**Comment by rmhubley** [comment]
Hi,
   This may be a problem for the "Maker" folks since they seem to have wrapped RepeatMasker/Modeler up in their package and I have no idea how they configured them to work together.  If you are installing these packages yourself then I am curious what happened when you ran "configure" inside the RepeatModeler directory when you installed it?  The error is not that it can't find the TRF program itself, rather it's telling you that it can't find the TRF.pm file.  This file is part of the RepeatMasker package ( a dependency of RepeatModeler ).  It does show that you have the path "/home/manager/Documents/maker/exe/RepeatMasker " in your include path.  Does this path really exist?  Does it contain the TRF.pm file?

**Comment by aberaslop** [comment]
Hi,
Thank you for your answer!
Yes, the path existed. And it did contain the TRF file. But you were onto
something. Somewhere in the internet I read that the file had to be named
TRF alone, which is what I had. (And it had been suggested to me in the
first comment). Unfortunately, that did not work for me. However, renaming
it to TRF.pm did.

Thank you to everyone that tried to help me! Maker runs smoothly now.
