### ISSUE TITLE
What is the default search engine used by BuildDatabase?

### ISSUE THREAD

**Issue by Ruiqi-CUB** [Dfam-consortium/RepeatModeler#224]
From the documentaion:
`-engine <engine name>
    The name of the search engine we are using. I.e abblast/wublast or
    ncbi (rmblast version).`

If I do not specify the search engine, what  is the default search engine used by BuildDatabase? 

For example, `BuildDatabase -name AnnotationDB Genome.fasta`

Thanks a lot

**Comment by rmhubley** [comment]
Currently on rmblast is supported.  The -engine parameter has been deprecated.
