### ISSUE TITLE
No space left on device Error 

### ISSUE THREAD

**Issue by Ruiqi-CUB** [Dfam-consortium/RepeatModeler#226]
I have the following error after running repeatmodeler: 

```
... ...
100% completed,  00:0:00 (hh:mm:ss) est. time remaining.
Comparison Time: 25:21:23 (hh:mm:ss) Elapsed Time, 1141860132 HSPs Collected
  - RECON: Running imagespread..
RECON Elapsed: 00:22:36 (hh:mm:ss) Elapsed Time
sort: write failed: 'standard output': No space left on device
sort: write error
sort failed for images/spread1.
```

There are plenty of space left in the disk, and I was wondering what is wrong. Could you please help me take a look?

The repeatmodeler was installed via conda: `conda install -c "bioconda/label/cf201901" repeatmodeler`

This is the command I run: `nohup RepeatModeler -pa 36 -database Tmax_modeler&`

**Comment by rmhubley** [comment]
Sorry I didn't get to this question back in November.  I suspect you have figured this out by now.  For the benefit of others, I would speculate that this was a transient issue created by some other process running on this system.  RepeatModeler simply calls the UNIX sort utility so if it reported that it was out of space, it probably was.
