### ISSUE TITLE
Thread option is not passed to RepeatClassifier

### ISSUE THREAD

**Issue by Alteroldis** [Dfam-consortium/RepeatModeler#227]
v2.0.5
In line 1718 you define thread option for classificator, but forgot insert it in command:
`$addlOpts = "-threads $options{'threads'} " if ( $options{'threads'} );
system(   "$FindBin::RealBin/RepeatClassifier "
          . "-consensi consensi.fa -stockholm families.stk" );`

**Comment by rmhubley** [comment]
Thanks for reporting this.  The fix will appear in the next release.
