### ISSUE TITLE
RepeatClassifier error "No database indicated or it is an empty file."

### ISSUE THREAD

**Issue by kdarragh1994** [Dfam-consortium/RepeatModeler#234]
I ran RepeatModeler and got consensi.fa and families.stk files. There was an error in the installation which prevented the final classification step so I wanted to re-run RepeatClassifier on the output files to classify them for RepeatMasker use. 

I ran RepeatClassifer using singularity like this:
singularity exec /N/slate/kdarrag/programs/dfam-tetools-latest.sif RepeatClassifier -consensi consensi.fa -stockholm families.stk

The only error message was "No database indicated or it is an empty file."
However neither consensi.fa nor families.stk are empty. 

Thank you for your help.
Kathy

**Comment by kdarragh1994** [comment]
The error message states "No database indicated or it is an empty file." and then shows the options for running Repeatclassifier. I tried with ./consensi.fa and it didn't work. I think you are right that it is an issue with the directories because I do not see my working directory when I follow the second step. What can I do to resolve this?

**Comment by asgray** [comment]
Singularity binds your working directory into the container by default ([as described here](https://docs.sylabs.io/guides/3.1/user-guide/bind_paths_and_mounts.html)), so it's likely that your admins (I assume you have admins) have disabled that feature for their own reasons. You might be able to make the binding by hand with `singularity exec -B $PWD /.../container.sif <args>`, but if that doesn't work you'll need to work with whoever is in charge of your system.
