### ISSUE TITLE
error in builddatabase

### ISSUE THREAD

**Issue by weirdo-onlooker** [Dfam-consortium/RepeatModeler#238]
During the database construction process, 
"BuildDatabase -name hhh_YQtrio0 -engine ncbi genome/hhh_YQtrio0.fasta" , I also tried to remove the engine option，
finally I received the following message:

Building database hhh_YQtrio0:
  Reading genome/hhh_YQtrio0.fasta...
The makeblastdb program exited with code 1.  Please check your input file(s) for potential formating errors.
/ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb returned: /ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb)
/ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb)
/ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb)
/ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb)

The command used was: /ifs1/User/lengliang/yaozc/biosoft/rmblast-2.14.1/bin/makeblastdb -blastdb_version 4 -out hhh_YQtrio0 -parse_seqids -dbtype nucl -in ./RM_9ImDCpo 2>&1
Died at /ifs1/User/lengliang/yaozc/biosoft/RepeatModeler-2.0.5/BuildDatabase line 331.

I have checked my fasta file and there seems to be no issue with it. I attempted to upgrade the GLIBC version, but failed and do not have root permissions. I also tried to downgrade the rmblast version to 2.11.0, but it requires reconfiguration, which also encountered issues. Now I want to replace rmblast with another software, and I don't want to rerun perl ./configure. Where can I modify this configuration file?

this is my fasta file(part):
>h1tg000001l
CTGAGTTTTCATGTATAATGATGAATTAGGCTAAGCATATGTTGCTTTATGTATGTAAATCTGTTTGTATGGTTGATTGTTTGTACTAAATTCACATTGTGATGCAGTTGCATTTCATATTATAATGCAGTAGGTTTTTATTTTAACTGTGATGCAGTAGGTTGTTTGT......

**Comment by lifan18** [comment]
Hi,

I also had this problem when I used rmblast-2.14.1. I fixed the issue "GLIBC_2.29 not found" by replacing the rmblast-2.14.1 with rmblast-2.14.0. 

Have a try!

Good luck!

Fan

**Comment by rmhubley** [comment]
If you would like to stick with the latest rmblast I would suggest simply compiling it from source (instructions here: http://www.repeatmasker.org/rmblast/ ).  This will ensure that the correct GLIBC is used when building the binary.
