### ISSUE TITLE
Problem with RepeatMasker after successful RepeatModeler run

### ISSUE THREAD

**Issue by pedres** [Dfam-consortium/RepeatModeler#244]
**Describe the issue**

I am trying to annotate some earthworm genomes but after RepeatModeler run RepeatMasker fails

**Reproduction steps**

BuildDatabase -name Amynthas Amynthas.fasta
RepeatModeler -database Amynthas -threads 50 -LTRStruct >& run.out 
RepeatMasker -pa 50 -a -lib Amynthas-families.fa Amynthas.fasta -e rmblast  -dir MASKED >& masker.txt 

link to genome
https://ngdc.cncb.ac.cn/gwh/Assembly/12838/show)

**Log output** 
RepeatMasker 

Please paste or attach any and all log output, which includes useful information including data file statistics and version numbers.  An easy way to capture this is to redirect the log output to a file e.g `RepeatModeler -database mydb >& output.log`.  The log output should include the "random seed" value at the start of the run.  This number will be necessary in order to reproduce the run exactly.

**Environment (please include as much of the following information as you can find out):**
[masker.txt](https://github.com/Dfam-consortium/RepeatModeler/files/15285534/masker.txt)

I am using RepeatModeler and RepeatMasker in a conda environment that only contains these tools (RepeatMasker version 4.1.5)
conda create --name repeatMOD
conda activate repeatMOD
mamba install repeatmodeler

So, the problem appears when I try to run RepeatMasker. If I run rhe command I wrote above in the masker.txt file I find several error messages noting that the program is not able to find some files. For example
CrossmatchSearchEngine::parseOutput: Unable to open results file: /media/pupepo/DATOS/genomas/amynthas/RM_1294310.SunMay121004582024/Amynthas.fasta_batch-37.cat : No such file or directory at /home/pupepo/miniconda3/envs/repeatMOD/bin/RepeatMasker line 4732

**Comment by rmhubley** [comment]
This looks to be a problem with RepeatMasker and in particular something wrong with your filesystem.  The inability for the software to open a file in this directory "/media/pupepo/DATOS/genomas/amynthas/RM_1294310.SunMay121004582024/" is causing it to fail.  Perhaps this is an NFS filesystem that went down during your run?  In addition I would not recommend using the conda versions of our tools.  We didn't create the recipes and we have had many issues relating to incorrect or dated conda installations.

**Comment by pedres** [comment]
Thanks a lot for your explanation. I was running RepeatModeler in a single workstation with a NTFS filesystem. I will try with the docker or singularity containers.

**Comment by rmhubley** [comment]
Or try a local non-NTFS filesystem to work in.  I am not at all sure how well this set of tools will work outside of a standard UNIX/NFS/EXT/XFS environment.

**Comment by pedres** [comment]
Hi,
I just tried in the home folder and it worked. I had  problems with length of fasta headers in RepeatMasker but I could solve it. Thanks a lot for your help.


Manuel
________________________________
De: Robert Hubley ***@***.***>
Enviado: martes, 18 de junio de 2024 21:45
Para: Dfam-consortium/RepeatModeler ***@***.***>
Cc: Manuel Aira Vieira ***@***.***>; Author ***@***.***>
Asunto: Re: [Dfam-consortium/RepeatModeler] Problem with RepeatMasker after successful RepeatModeler run (Issue #244)


Or try a local non-NTFS filesystem to work in. I am not at all sure how well this set of tools will work outside of a standard UNIX/NFS/EXT/XFS environment.
