### ISSUE TITLE
The problem of LTRpipline

### ISSUE THREAD

**Issue by duan12345678** [Dfam-consortium/RepeatModeler#245]
Hi.
I encountered the following problem during the run. Changing the server and increasing the value of -pa did not resolve the issue. Below are my command and the error. Could you please help me figure out how to solve this problem?

RepeatModeler -pa 40 -database Genome -LTRStruct > repeatmodeler.run.out
LtrPipeline: GenomeTools failed to run ltrharvest, Error code: 9109504
Ltrharvest returned an unexpected result line:
LtrPipeline:Segmentation fault (core dumped)

**Comment by rmhubley** [comment]
This is a problem with the GenomeTools program.  Perhaps it's caused by this issue: #202
