### ISSUE TITLE
Possible version instability between RepeatModeler v2.0.1 and v2.0.4 (and v2.0.5)

### ISSUE THREAD

**Issue by casparbein** [Dfam-consortium/RepeatModeler#250]
**Describe the issue**

We recently updated the RepeatModeler version used on our HPC cluster from 2.0.1 to 2.0.4 and shortly after to 2.0.5. When running RepeatModeler and RepeatMasker on very similar genomes and inspecting the repeat landscape plots, we saw stark difference in the divergence level and genome coverage of some elements. To systematically test this, we ran RepeatModeler v2.0.1 and v2.0.4  on the Orca genome assembly GCA_937001465.1 (https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_937001465.1/) and Saddleback Dolphin genome assembly GCA_030062865.1 (https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_030062865.1/) followed by a RepeatMasker v4.1.6 run.  I also added the v2.0.5 results here although I don't have log files for them.

These are the respecitve landscape plots:
![grafik](https://github.com/user-attachments/assets/5a986247-36dd-4c03-adc9-6885e8dc1303)

![grafik](https://github.com/user-attachments/assets/a4a37f71-abcd-4b2f-b3cf-cad36e718175)

All three landscape plots differ to a degree where we are unsure what the common repeat features in the Orca and Dolphin genomes are. Do you have any suggestions which run to use? I am aware that it is desirable to use a manually curated library, but even then, which RepeatModeler run should be used to start that process?

**Reproduction steps**
 
We ran RepeatModeler using the following commands (example for Orca):
```
module unload repeatmodeler; module load repeatmodeler/2.0.1
BuildDatabase -name orcOrc1_201 orcOrc1.fa >> orcOrc1_201.log.model 2>> orcOrc1_201.log.model
RepeatModeler -pa 30 -database orcOrc1_201 &>> orcOrc1_201.log.model

module unload repeatmodeler; module load repeatmodeler/2.0.4
BuildDatabase -name orcOrc1_204 orcOrc1.fa >> orcOrc1_204.log.model 2>> orcOrc1_204.log.model
RepeatModeler -threads 100 -database orcOrc1_204 &>>orcOrc4_204.log.model
```

RepeatMasker v4.1.6 was run using the following commands:
```
module unload repeatmasker; module load repeatmasker/4.1.6
RepeatMasker -e rmblast -pa 30 -a -dir orcOrc1_204_RepMask -lib orcOrc1_204-families.fa orcOrc1.fa

module unload repeatmasker; module load repeatmasker/4.1.6
RepeatMasker -e rmblast -pa 30 -a -dir orcOrc1_201_RepMask -lib orcOrc1_201-families.fa orcOrc1.fa
```

RepeatModeler v2.0.5 and subsequently RepeatMasker v4.1.6 were run as part of a larger pipeline, but generally using the same commands as specified above.

The repeat landscape plots were created using the following commands (and plotted in R, example for Orca):
```
/beegfs/software/RepeatMasker/RepeatMasker-4.1.6/util/calcDivergenceFromAlign.pl \
-s orcOrc1_204_RepMask/orcOrc1_204.divsum \
 orcOrc1_204_RepMask/orcOrc1.fa.align
/beegfs/software/RepeatMasker/RepeatMasker-4.1.6/util/calcDivergenceFromAlign.pl \
-s orcOrc1_201_RepMask/orcOrc1_201.divsum \
orcOrc1_201_RepMask/orcOrc1.fa.align
```

**Log output** 

These are the log outputs for orcOrc1.1: 
[orcOrc1_201.log.model.txt](https://github.com/user-attachments/files/16313731/orcOrc1_201.log.model.txt)
[orcOrc1_204.log.model.txt](https://github.com/user-attachments/files/16313732/orcOrc1_204.log.model.txt)

and for delDel: 
[delDel_201.log.model.txt](https://github.com/user-attachments/files/16313733/delDel_201.log.model.txt)
[delDel_204.log.model.txt](https://github.com/user-attachments/files/16313734/delDel_204.log.model.txt)

**Environment (please include as much of the following information as you can find out):**

All runs were done with perl v5.32.1 loaded.
All RepeatModeler versions were manually installed on a HPC.
RepeatMasker dependency of RepeatModeler v2.0.1 according to the output log: v4.1.0 (repeat masking was done with v4.1.6)
RepeatMasker dependency of RepeatModeler v2.0.4 according to the output log: v4.1.4 (repeat masking was done with v4.1.6)
Operating system: Linux 4.18.0-513.11.1.el8_9.x86_64 #1 SMP Wed Jan 10 22:58:54 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rmhubley** [comment]
There is much to unpack here...and thank you for the detailed information.  I wouldn't call this a stability issue as de-novo identification is improving over time and this is a sampling strategy so the results will vary both by version and by run.  Obviously one would hope they get better by version.  It's a bit problematic to evaluate the de-novo results using landscape plots for a couple of reasons: 1) the classification of identified families is dependent on the content of the reference database used in the comparisons (in this case RMod 2.01 was using RMsk 4.1.0, and RMod 2.04 was using RMsk 4.1.4 -- and I don't know if RepBase was included with either RMsk installation), and 2) the divergence is dependent on the family definition itself which varies due to sampling differences, subfamily structure and fragmentation of the consensus models.   

 I am happy to see that with later versions the "unknown" classification drops significantly, and that the family count, and mask levels are not wildly different between runs.  In order to get an accurate landscape you will have to manually curate a library by extending these fragments into full-length elements, correcting classifications, and remove redundant models.  Which one should you use -- I would favor the latest version of RepeatModeler, but you can still use the additional information in the other runs to fill in any missing families ( e.g look for unique sequences in 2.0.1/2.04 and add them to the 2.0.5 library).  

There could still be other reasons why these three landscapes look different, but without looking deeply into the libraries themselves its hard to say what they may be.

**Comment by casparbein** [comment]
Thank you for your quick response. Two small additions: 

- The percentage of each genome getting masked after modelling is roughly similar, with RMod 2.04 showing a ~2% reduction (Orca RMod 2.01: 43.99%; Orca RMod 2.04: 42.00 %; Dolphin RMod 2.01: 42.52 %; Dolphin RMod 2.04: 40.82 %), so for genome alignment purposes, it does not really matter which version is used.
- Earlier, we ran RMod 2.01 on several other assemblies (and unfortunately without retaining the log files properly) two to three times and inspected the landscape plots, which where very congruent across the board, so I think the majority of differences between the runs reported here are caused by differences in RepeatModeler versions.

Since I lack expertise and experience in manually curating repeat libraries, we will for now resort to running established Dfam libraries as input for RepeatMasker on the assemblies in question. As a general note, and I might be wrong here, I assume that many people will run RepeatModeler without extensive manual curation and report the results, for example as landscape plots, in publications. Case in point, we have seen some published landscape plots that made us question the veractiy of our own results, only to realize that a different RMod version was used compared to our own runs. It therefore seems conceivable that systematic differences between versions lead to systematic changes in the modelled libraries that could be summarized verbally as something like: "RepeatModeler v2.0.1 consistently overestimates divergence levels and length of LINE/L1 elements" (toy example). 

As a next step on my side, I'll try to merge and CD-hit the two (or three) libraries per assembly to see which families are unique to which version and whether I can find clear false-positives.

Thanks again,
Bernhard

**Comment by rmhubley** [comment]
I agree that it is unwise to use de-novo TE pipelines to draw conclusions about TE evolution.  David Ray's paper awhile back directly addressed this issue:

```
Cibele G. Sotero-Caio, Roy N. Platt, Alexander Suh, David A. Ray, Evolution and Diversity of Transposable Elements in Vertebrate Genomes, Genome Biology and Evolution, Volume 9, Issue 1, January 2017, Pages 161–177, https://doi.org/10.1093/gbe/evw264
```

I don't know that I agree with the statement that RepeatModeler consistently overestimates divergence levels.  But I do agree that one cannot make strong conclusions about the true divergence levels of TE classes simply from de novo generated libraries.

**Comment by casparbein** [comment]
Thanks for the reference, I'll take a look at this. 
Sorry for the misunderstanding, I didn't mean to imply that RepeatModeler does consistently overestimate divergence levels or anything, this "RepeatModeler v2.0.1 consistently overestimates divergence levels and length of LINE/L1 elements" was thought as a random example sentence referring to something that I'd like to be able to say about the different versions, seeing the consistent differences between versions. Maybe this is hard to do and requires a deep dive into the actual difference between families in the respective libraries.
