### ISSUE TITLE
The latest version of dfam/tetools?

### ISSUE THREAD

**Issue by Abieskawa** [Dfam-consortium/RepeatModeler#259]
**What do you want to know?**
I just want to ask what is the "latest" tag version of dfam/tetools downloaded from docker hub (2024/10/2), it seems not to be 1.89.2, right?
**Helpful context**
-
* Is there a particular genome assembly or organism your question is about? If possible, please provide a link to a publicly available assembly and/or a species name.
-
* Have you installed RepBase RepeatMasker Edition for RepeatMasker? This question is especially relevant for questions about classification or the `RepeatClassifier` program.
Yes, but it configured by my colleague, I just mount to the container.

Thanks

**Comment by asgray** [comment]
HI @Abieskawa, the latest tag at the time you posted this question should have referred to version 1.89.2. If that wasn't the case, I must have missed pushing out that tag.

Currently the latest version of TETools is 1.90, and is tagged as such.
