### ISSUE TITLE
Can not find the library containing classification information

### ISSUE THREAD

**Issue by YouxinZhao** [Dfam-consortium/RepeatModeler#261]
The result
![image](https://github.com/user-attachments/assets/31117dcd-a847-478c-a31c-31bf05384054)
The program seems finished
![image](https://github.com/user-attachments/assets/e80f2cb8-3418-4fa7-af3e-bb06318114ca)

**Comment by YouxinZhao** [comment]
![image](https://github.com/user-attachments/assets/b560eb33-44aa-41e2-94a3-97c0f6811750)

**Comment by rmhubley** [comment]
Yes, it seems to have finished.  What is the question exactly?
