### ISSUE TITLE
about -recoverDir 

### ISSUE THREAD

**Issue by AnnieBunny0726** [Dfam-consortium/RepeatModeler#262]
hi,
   Because there is error during the sixth run and i was going to use the  -recoverDir module to recover, I got this error message

RepeatModeler Version open-1.0.8
================================
Search Engine = ncbi
Database = F .
  - Sequences = 73
  - Bases = 295140030
Undefined subroutine &main::abs_path called at /data1/NFS/home/scau544/.conda/envs/mamba/envs/repeat_annotation/share/RepeatModeler/RepeatModeler line 364.

I went looking for the code around 364, but still don't know what the problem is
if ( $options{'recoverDir'} && -d $options{'recoverDir'} )
{
  my $recoverDir = $options{'recoverDir'};
  $tmpDir = abs_path( $recoverDir );
  ## Determine highest successful round
  my $i                = 0;
  my $highestGoodRound = 0;

**Comment by rmhubley** [comment]
You are missing the perl module "Cwd" on this system.  This can happen if the program was installed in a shared directory from one computer (where the configure script will check for missing perl modules) and then subsequently run on another where the module is not available ( perhaps a local vs shared perl installation ).  Additionally this looks like a conda installation which I don't recommend for our tools.
