### ISSUE TITLE
Question about ‘Running all-by-other comparisons’

### ISSUE THREAD

**Issue by YPGG1234** [Dfam-consortium/RepeatModeler#36]

**Comment by YPGG1234** [comment]
I found that I had one software -- nseg is not installed, after installation , this problem was solved , but a new problem appeared : 
```
...
Program duration is 156.0 sec = 2.6 min = 0.0 hr
   - Collecting repeat instances...
 -- Refining Family R=136 / 0 ( RS Elements: 19607, Using 100 ):
RepeatModeler: Could not open refined model
```
just as #35 described , can somebody help me ?

**Comment by Maulik23** [comment]
Hi @YPGG1234 , 

Try reinstalling RepeatModeler from git source codes. I had read somewhere that RepeatModeler from conda had some problems.

**Comment by YPGG1234** [comment]
Thank u @Maulik23  !
Now I have a new problem, which is the program runs to
`Running all - by - other comparisons..`
It stopped at this step, my test file size was only 80K, but It stopped for a day and didn't respond, which is not normal.Do you know why?

**Comment by Maulik23** [comment]
Hi @YPGG1234, 

Can you check your log file for the errors? Also check that Refiner program is working properly. For me, the problem got resolved after I cloned the RepeatModeler repository from git and followed the steps as exactly mentioned in the Read me page. Hope it helps.

**Comment by rmhubley** [comment]
Could you send me (rhubley@systemsbiology.org) a copy of the screen output for this last run?  A few other things that would help me address this issue:

  1. Where you got the RepeatModeler package and which version you are running
  2. The search engine you are using and the version
  3. A copy of the "RM_#..." directory created for this run.  

-Robert
