### ISSUE TITLE
sampleDB-1.fa.rscons.filtered is empty, but other files in the round-1 directory are not

### ISSUE THREAD

**Issue by savytskanatalia** [Dfam-consortium/RepeatModeler#41]
I ran RM for at least 2 weeks and it seemed to be generating a lot of output files. During the round 6 RM was killed. When trying to recover, it turned out in round-1 though sampleDB-1.fa, sampleDB-1.fa.lfreq and sampleDB-1.fa.rscons were non-empty, the sampleDB-1.fa.rscons.filtered file is 0, and the following round folders are filled with a lot of generated intermediate files....
My question is, is there any possibility of recovery for this run? Like using the already generated in the round-1 files for sampleDB-1.fa.rscons.filtered?

And also, why would RM fail to generate sampleDB-1.fa.rscons.filtered, if everything else was in place? And why would it keep running and generating multiple intermediate files in following rounds, if the main file from round-1 was empty in the first place? 

My version of RM is  repeatmodeler 1.0.11; I used perl v5.26.2, RepeatScout Version 1.0.5, RECON 1.08.

**Comment by rmhubley** [comment]
Sorry for the delay and sorry you had a problem at the very last stage of the analysis.  First, to answer your question about the .filtered file.   This is generated by the RepeatScout package script filter-stage-1.prl.  This script looks at the sampleDB-1.fa.rscons file and removes any consensus sequences that appear to composed of mostly tandem repeat sequences.  It is not impossible that all families discovered at this stage could be just tandem repeats, although it's not commonly the case.  Either way, it should not prohibit the program from continuing on to the next round.  It just means that RepeatScout didn't contribute any families to this run.  After round-1 is complete the remaining rounds are RECON-based.  Each round provides RECON an increasingly larger input sample and should generate quite a bit of intermediate files in those directories.  

Now, as to why it failed and how to recover.  It is best to keep the screen output from a RepeatModeler run and the corresponding RM_* directory.  Both of these can be used to debug the problem and hopefully recover after a failure.  Please send me the log file if you have it still.  As for recovery have you tried running ./RepeatModeler -recoverDir <RM_your_output_directory>?  What did the program output when you did that?

**Comment by xiaoyezao** [comment]
Hi, I encountered the same problem as @savytskanatalia posted. The program finished its work with the following lines at the end of the log: 
```
Discovery complete: 0 families found
Program Time: 92:47:22 (hh:mm:ss) Elapsed Time
Working directory: /PARA/pp427/project/rheum/annotation/RepeatModeler/RM_5636.TueOct220330482019 may be deleted unless there were problems with the run.
No families identified.  Perhaps the database is too small or contains overly fragmented sequences.
```
I rerun the program with the `-recoverDir` option, and it reports:
```
Oops...the /PARA/pp427/project/rheum/annotation/RepeatModeler/RM_5636.TueOct220330482019 run did not get passed round-1.
It makes more sense to restart this run from the beginning.
Remove the -recoverDir option and rerun the program.
```
I checked the output file: in round-1, sampleDB-1.fa.rscons.filtered is empty, and no consensi.fa and .html files was generated; in round-2/-6, a lot of intermediate files; and the final consensi.fa and families.stk are both empty.

It seems that the program running is successful, but just no repeats were identified, which is odd.
My assembly is 1.4G with 940 contigs and N50=5M. It's unlikely there are no repeats in the genome.

Please find the attached log file. Do you have any ideas what's wrong here?

Thanks

[slurm-2714034.txt](https://github.com/Dfam-consortium/RepeatModeler/files/3774443/slurm-2714034.txt)

**Comment by rmhubley** [comment]
There is a new version of RepeatModeler out.  I am closing this for now.  If you are still having problems please let us know.
