### ISSUE TITLE
-recoverDir option useless because round-1 apparently failed

### ISSUE THREAD

**Issue by marcopessoa** [Dfam-consortium/RepeatModeler#47]
This is the same issue reported previously (#21). I am running `RepeatModeler version 2.0`, just released.

The `round-1` directory does not contain `consensi.fa` and `sampleDB-1.fa.rscons.filtered` is empty. In addition, `repeatscout.log` is empty as well and filter-stage-1.log says 

`/usr/local/bin/filter-stage-1.prl: No such file or directory`

Although `round-1` fails the pipeline continues. I found a problem with `LTR_retriever` and it would be great to resume the pipeline from that point and not from the start.

Where should I look for `filter-stage-1.prl` to put it in the right location?

**Comment by jebrosen** [comment]
`filter-stage-1.prl` is part of `RepeatScout`. It looks like the configuration system does not check for that file but it could (it currently only checks for `RepeatScout` and `build_lmer_table`). 

What method did you use to install `RepeatScout` that didn't include that file?

**Comment by marcopessoa** [comment]
Ok, I've just found `filter-stage-1.prl` in the `RepeatScout` directory. I will fix my paths and try again. Thanks!
