### ISSUE TITLE
Refiner line 395 error

### ISSUE THREAD

**Issue by pondlifepondlife** [Dfam-consortium/RepeatModeler#50]
Hi, 

I'm running RepeatModeler on many genomes and I'm getting an issue with one genome. I previously ran RepeatMasker successfully using the "eukaryotes" default database with this genome, and am now trying to run it with a de novo database that I build with RepeatModeler, and I get this output in the error log ever time:

RepeatModeler -engine ncbi -pa 8 -database $my_genome_db

Program duration is 537.0 sec = 8.9 min = 0.1 hr
MultAln::buildConsensusFromArray: Matrix alphabet doesn't include
the letters: A, H
 at /nfs/sw/repeatmodeler/repeatmodeler-1.0.11/Refiner line 395.
RepeatModeler: Could not open refined model /gpfs/commons/groups/amnh/sally/other_genomes/RM_167497.MonDec91231592019/round-1/family-5.fa.refiner_cons!

It's always the same error, but with a different family each time, family-3, family-4, family-5 etc.

I'm running exactly the same command with every other genome and it works no problem. How do I figure out what's going wrong with this one? 

Thanks!

**Comment by jebrosen** [comment]
This looks like the problem described previously at https://github.com/Dfam-consortium/RepeatModeler/issues/2#issuecomment-304073419.
