### ISSUE TITLE
Mafft --large option not found

### ISSUE THREAD

**Issue by deoliveira86** [Dfam-consortium/RepeatModeler#52]
Dear developers,

After almost five days of execution time my RepeatModeler run came to an end, however I noticed a minor error during the last step of the LTR Structural Analysis (the only error that I got from the whole run). It seems that in the end of the LTR structural analysis mafft is invoked with an option called ``--large``, that is not recognised by the software which prevented the generation of the MSA file from the denovo LTR results. 

> LTR Structural Analysis
> Running LtrHarvest...     : 24:02:44 (hh:mm:ss) Elapsed Time
> Running Ltr_retriever...  : 01:06:48 (hh:mm:ss) Elapsed Time
> Aligning instances...Unknown option:  --large
> LTRPipeline: Error - could not produce a multiple alignment from the denovo LTR results.
> LTRPipeline Time: 25:09:34 (hh:mm:ss) Elapsed Time

I would like to ask two questions:

1. How important is this step for the generation of the consensi.fa? Will this impact the number of predicted families at the end of the RepeatModeler run? If yes, how can I fix this problem without running RepeatModeler from the beginning? I have two files within the LTR folder: LtrRetriever-redundant-results.fa and raw-struct-results.txt

2. Which version of mafft uses the --large option? I looked in the mafft website and I could not find it.

Best regards,
André

Software information:
RepeatModeler version: ``2.0``
Mafft version: ``v7.310``
LTR_retriever version: ``2.8``
LTR_pipeline: ``2.0``

**Comment by deoliveira86** [comment]
Hello,

I just realised that I was using an older version of mafft. From the RepeatModeler website:

> MAFFT - A multiple sequence alignment program. We developed and tested RepeatModeler using mafft version 7.407. Please use this verison or higher from here: https://mafft.cbrc.jp/alignment/software/

Just the question #1 now is to be answered.

Many thanks,
André

**Comment by jebrosen** [comment]
> How important is this step for the generation of the consensi.fa? Will this impact the number of predicted families at the end of the RepeatModeler run?

Without this step, the LTR structural search results will not be included and your output would be similar to that from RepeatModeler 1.0.11 (which did not include the LTR search). The exact impact will depend on the prevalence and intactness of LTRs in the genome, but you will likely see fewer and/or lower-quality (i.e. fragmented) LTR families.

> If yes, how can I fix this problem without running RepeatModeler from the beginning? I have two files within the LTR folder: LtrRetriever-redundant-results.fa and raw-struct-results.txt

The `-recoverDir` option might work, resuming at the last successful round and going to `LTRPipeline` next. If `recoverDir` does not work `LTRPipeline` can be run standalone to find out what is missing, however the merging of results between the RECON+RepeatScout and the LTRPipeline methods is not set up to run standalone.

**Comment by deoliveira86** [comment]
Thanks for the info. I will try to run again with the newer version of mafft and see if it proceeds until the very end.
