### ISSUE TITLE
LTR Structural Analysis could not cluster MAFFT results

### ISSUE THREAD

**Issue by elor77** [Dfam-consortium/RepeatModeler#53]
Hi 
When trying to run RepeatModeler with LTR got the following error:
```
LTR Structural Analysis
=======================
Running LtrHarvest...     : 01:50:25 (hh:mm:ss) Elapsed Time
Running Ltr_retriever...  : 00:10:55 (hh:mm:ss) Elapsed Time
Aligning instances...     : 00:18:46 (hh:mm:ss) Elapsed Time
Clustering...sh: line 1:  6551 Aborted                 (core dumped) /programs/NINJA-0.97/NINJA/Ninja --in /local/workdir/eoren/melons/genomes/DUL/RM_12272.TueDec241438072019/LTR_26929.WedDec252128312019/mafft-alignment.fa --out /local/workdir/eoren/melons/genomes/DUL/RM_12272.TueDec241438072019/LTR_26929.WedDec252128312019/NINJA_26929.WedDec252348372019/cluster.dat --out_type c --corr_type m --cluster_cutoff 0.2 --threads 32 > /local/workdir/eoren/melons/genomes/DUL/RM_12272.TueDec241438072019/LTR_26929.WedDec252128312019/NINJA_26929.WedDec252348372019/Ninja.log 2>&1
LTRPipeline: Error - could not cluster MAFFT results.
```
Any idea what could cause this? 
I it possible to resume just from the LTR pipeline stage?

**Comment by jebrosen** [comment]
> Any idea what could cause this?

Possibly an out-of-memory or similar condition, or the input dataset is much larger than anticipated. If you can share the contents of `/local/workdir/eoren/melons/genomes/DUL/RM_12272.TueDec241438072019/LTR_26929.WedDec252128312019/NINJA_26929.WedDec252348372019/Ninja.log` that may help debug the issue.

> Is it possible to resume just from the LTR pipeline stage?

Unfortunately, I don't believe it currently is.

**Comment by elor77** [comment]
`Ninja.log` and the NINJA sub-directory are missing (or weren't created in the firs place). 
I couldn't find the `core.dump` file either. 
I thought that it might be a memory issue and am doing a rerun with limited multi-threading.

**Comment by elor77** [comment]
I've confirmed this is not an out-of memory issue. 
It happened immediately after finishing the alignment stage. 
Unfortunately, once the script moves to the next step all subfolders from previous step are deleted making it hard to debug. 
e.g `LRET_4465.FriDec271452502019` was deleted once aligning started (along with 'LTR_retriever.log' ,and  `MAFFT_4465.FriDec271504442019` was deleted later too. 
I guess the same happened to the `Ninja.log` 
Might want to change that.

**Comment by elor77** [comment]
I managed to run ninja manually on `mafft-alignment.fa`
The eeror in `Ninija.log`:
`Invalid out_type:  try  'd' or 't'.Critical Error, aborting.`
It appears the error is caused by invalid parameter in `--out type c`

**Comment by elor77** [comment]
The problem was caused because I was using  NINJA version 0.97 instead of NINJA 0.95-cluster_only

Happy new year.

**Comment by jebrosen** [comment]
We (and/or NINJA) should definitely improve the error message in that case and not delete the log files. Thank you for reporting this!
