### ISSUE TITLE
Extra files generated from a test run

### ISSUE THREAD

**Issue by stefaniehoho** [Dfam-consortium/RepeatModeler#54]
Hi All,

I've done a test tun of RepeatModeler 2 on a test genome. It seemed at least partially working but I found extra files generated from the run which were not specified in the output lists. I'm new to repeatmodeler so I'm not sure if it ran through or came across some issues.

1.  tmpMaskDB-* files from RM_xxxxxx/round-2 to round-6 folders
The whole lists included:
tmpMaskDB-1-gilist
tmpMaskDB-1-gilist.txt
tmpMaskDB-1.nhr
tmpMaskDB-1.nin
tmpMaskDB-1.nnd
tmpMaskDB-1.nni
tmpMaskDB-1.nog
tmpMaskDB-1.nsq

2. Three unspecified files generated in the RM_xxx folder.
consensi.fa.classified
families-classified.stk
tmpConsensi.fa

3. Outside RM_xxx folder.
test-families.fa
test-families.stk
test.nhr
test.nin
test.nnd
test.nni
test.nog
test.nsq
test.translation

I guess these files are temporary files generated during the run but I cannot find any error from the log file attached below. Could you please help me pinpoint the step which the program potentially failed?

Thank you very much.

[RM_log.txt](https://github.com/Dfam-consortium/RepeatModeler/files/4027676/RM_log.txt)

**Comment by jebrosen** [comment]
Most of those extra files are normal--the help text in `README.md` just doesn't list every single one (some of them are probably new and were not added to that list).

* The main output files `test-families.fa` and `test-families.stk` are described just before the  file listing:

  > At the succesful completion of a run, two files are generated:
  >
  >     <database_name>-families.fa  : Consensus sequences
  >     <database_name>-families.stk : Seed alignments
  > 
  > The seed alignment file is in a Dfam compatible Stockholm format and may be uploaded to the Dfam database by submiting the data to help@dfam.org. In the near future we will provide a tool for uploading families directly to the database.
* `test.nhr`, `test.nin`, etc. - These are indexes of `test.fa` that are created by RMBlast (based on NCBI Blast+). The exact set of files depends on what version of RMBlast is being used and would also be different if you used a search engine other than RMBlast.
* `consensi.fa.classified` - temporary files, copied to `test-families.fa` and `test-families.stk` once RepeatModeler has finished
* `tmpMaskDB-*`, `tmpConsensi.fa` - more temporary files

As far as I can tell from that log RepeatModeler is working properly; the actual quality of the output will of course depend on the input genome. The extra files are kept around in case there are problems, which would usually (but not always) result in RepeatModeler failing early.

**Comment by stefaniehoho** [comment]
Hi Jeb, 

Thank you so much for your verification.

Actually, there is a sentence in the log file confused me since I was still able to see the RM_xxx folder.
> Working directory:  /LabShares/test_repeatremodeler/RM_29914.FriJan31710442020
> may be deleted unless there were problems with the run.

I'm so glad it worked. Thanks!

**Comment by jebrosen** [comment]
I think I see where the confusion came from now. That message means "may be deleted *by you*" (and that you should only need those files if you find problems with the run and need to reach out for help).
