### ISSUE TITLE
Error: [blastdbcmd] DB contains no accession info.

### ISSUE THREAD

**Issue by VoronDM** [Dfam-consortium/RepeatModeler#55]
Hi!

I'm getting the error at the start of RepeatModeler v2.0:
```
[user@GenomeBiology RepeatModeler-2.0]$ ./BuildDatabase -name Duni /Seq/Work/2019/RepeatWork/D_uni.fa
Building database Duni:
  Reading /Seq/Work/2019/RepeatWork/D_uni.fa...
Number of sequences (bp) added to database: 4430457 ( 2155765762 bp )
[user@GenomeBiology RepeatModeler-2.0]$ ./RepeatModeler -database Duni -pa 20 -LTRStruct
RepeatModeler Version 2.0
=========================
Search Engine = rmblast
LTR Structural Analysis: Enabled
Random Number Seed: 1578580938
Database = Duni ............................................................................................................................................................................................................................................................................................................................................................................................................................................................
  - Sequences = 4430457
  - Bases = 2155765762
  - N50 = 107004
  - Contig Histogram:
  Size(bp)                                                        Count
  -----------------------------------------------------------------------
  6891702-7383960 |                                                   [  ]
  6399445-6891702 |                                                   [  ]
  5907188-6399445 |                                                   [ 1 ]
  5414930-5907187 |                                                   [ 2 ]
  4922673-5414930 |                                                   [ 4 ]
  4430416-4922673 |                                                   [ 6 ]
  3938158-4430415 |                                                   [ 5 ]
  3445901-3938158 |                                                   [ 7 ]
  2953644-3445901 |                                                   [ 18 ]
  2461386-2953643 |                                                   [ 14 ]
  1969129-2461386 |                                                   [ 33 ]
  1476872-1969129 |                                                   [ 69 ]
  984614-1476871  |                                                   [ 109 ]
  492357-984614   |                                                   [ 319 ]
  100-492357      |************************************************** [ 4429869 ]

Using output directory = /home/user/distr/RepeatModeler-2.0/RM_9880.ThuJan91747232020
Storage Throughput = excellent ( 1046.63 MB/s )

Ready to start the sampling process.
INFO: The runtime of RepeatModeler heavily depends on the quality of the assembly
      and the repetitive content of the sequences.  It is not imperative
      that RepeatModeler completes all rounds in order to obtain useful
      results.  At the completion of each round, the files ( consensi.fa, and
      families.stk ) found in:
      /home/user/distr/RepeatModeler-2.0/RM_9880.ThuJan91747232020/
      will contain all results produced thus far. These files may be
      manually copied and run through RepeatClassifier should the program
      be terminated early.


RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
Error: [blastdbcmd] DB contains no accession info.
FastaDB::compact - Error could not locate file /home/user/distr/RepeatModeler-2.0/RM_9880.ThuJan91747232020/round-1/sampleDB-1.fa!
 at ./RepeatModeler line 829.
```
```
[user@GenomeBiology RepeatModeler-2.0]$ rmblastn -version
rmblastn: 2.10.0+
 Package: blast 2.10.0, build Dec 19 2019 13:31:35
```
```
[user@GenomeBiology RepeatModeler-2.0]$ RepeatMasker
RepeatMasker version open-4.0.9
```

**Comment by jebrosen** [comment]
Does the same genome file work with the previous release of RMBlast, 2.9.0? It is available at http://repeatmasker.org/RMBlast.html

**Comment by jebrosen** [comment]
I have reproduced the problem. `BuildDatabase` with RMBlast 2.10.0 generates a database that cannot be sampled by RepeatModeler. I will add a notice on the RMBlast download page while we determine how best to resolve this incompatibility.

**Comment by jebrosen** [comment]
Update: this has been worked around in RepeatModeler 2.0.1 by instructing RMBlast to always build a database in the v4 format, which is the default in RMBlast 2.9.0.

**Comment by VoronDM** [comment]
Thanks. Program finished without errors when used RMBlast 2.9.0.

**Comment by a2433522322** [comment]
> Update: this has been worked around in RepeatModeler 2.0.1 by instructing RMBlast to always build a database in the v4 format, which is the default in RMBlast 2.9.0.

rmblast                   2.10.0               h2d02072_0    bioconda
Hello. I've already updated the rmblast after 2.9.0, but I still get this error.   Random Number Seed: 1735874508
Database = R498.genome .
  - Sequences = 14
  - Bases = 390983850
Using output directory = /public2/home/chenweilan/ref/RM_114801.FriJan31122002025
Storage Throughput = good ( 984.87 MB/s )

Ready to start the sampling process.
INFO: The runtime of RepeatModeler heavily depends on the quality of the assembly
      and the repetitive content of the sequences.  It is not imperative
      that RepeatModeler completes all rounds in order to obtain useful
      results.  At the completion of each round, the files ( consensi.fa, and
      families.stk ) found in:
      /public2/home/chenweilan/ref/RM_114801.FriJan31122002025/ 
      will contain all results produced thus far. These files may be 
      manually copied and run through RepeatClassifier should the program
      be terminated early.


RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
Error: [blastdbcmd] DB contains no accession info.
FastaDB::compact - Error could not locate file /public2/home/chenweilan/ref/RM_114801.FriJan31122002025/round-1/sampleDB-1.fa!
 at /public2/home/chenweilan/anaconda3/envs/cresil/bin/RepeatModeler line 862
