### ISSUE TITLE
Miscalculation of contigs for histogram

### ISSUE THREAD

**Issue by giyany** [Dfam-consortium/RepeatModeler#57]
Hi,

This seems like a rather minor issue, albeit potentially confusing for the user, so I thought it wouldn't hurt to report:
while running RepeatModeler (V 2.0) I noticed that one of the contigs in my fasta is missing from the histogram. The number of sequences is correct, yet the number of contigs in the histogram summarizes to 2320 and it specifically seems to miss one of the largest contigs:

RepeatModeler Version 2.0
=========================
Search Engine = rmblast
LTR Structural Analysis: Disabled [use -LTRStruct to enable]
Random Number Seed: 1579614023
Database = Tillandsia_fasciculata .
  - Sequences = 2321
  - Bases = 837577910
  - N50 = 21704838
  - Contig Histogram:
  Size(bp)                                                        Count
  -----------------------------------------------------------------------
  30018350-32162447 |                                                   [ 4 ]
  27874254-30018350 |                                                   [ 1 ]
  25730157-27874253 |                                                   [ 5 ]
  23586061-25730157 |                                                   [ 5 ]
  21441965-23586061 |                                                   [ 1 ]
  19297868-21441964 |                                                   [ 3 ]
  17153772-19297868 |                                                   [ 1 ]
  15009675-17153771 |                                                   [ 2 ]
  12865579-15009675 |                                                   [ 1 ]
  10721483-12865579 |                                                   [ 1 ]
  8577386-10721482  |                                                   [  ]
  6433290-8577386   |                                                   [  ]
  4289193-6433289   |                                                   [  ]
  2145097-4289193   |                                                   [  ]
  1001-2145097      |************************************************** [ 2296 ]

Here are size estimates for the 25 largest contigs within the file I'm working with:

Scaffold_2199;HRSCAF=2643_pilon_pilon	32162447
Scaffold_658;HRSCAF=858_pilon_pilon	31698969
Scaffold_2318;HRSCAF=2902_pilon_pilon	31153634
Scaffold_2041;HRSCAF=2348_pilon_pilon	30972320
Scaffold_2096;HRSCAF=2455_pilon_pilon	30145683
Scaffold_2315;HRSCAF=2899_pilon_pilon	29567185
Scaffold_2317;HRSCAF=2901_pilon_pilon	27230796
Scaffold_2287;HRSCAF=2840_pilon_pilon	27210704
Scaffold_326;HRSCAF=476_pilon_pilon	26509606
Scaffold_1174;HRSCAF=1416_pilon_pilon	26021936
Scaffold_2314;HRSCAF=2898_pilon_pilon	25842354
Scaffold_2313;HRSCAF=2897_pilon_pilon	25341332
Scaffold_2225;HRSCAF=2709_pilon_pilon	24881768
Scaffold_1383;HRSCAF=1639_pilon_pilon	24649150
Scaffold_819;HRSCAF=1031_pilon_pilon	23784123
Scaffold_15;HRSCAF=48_pilon_pilon	23642332
Scaffold_2073;HRSCAF=2415_pilon_pilon	21704838
Scaffold_2321;HRSCAF=2905_pilon_pilon	21234157
Scaffold_2320;HRSCAF=2904_pilon_pilon	19440187
Scaffold_346;HRSCAF=503_pilon_pilon	19367790
Scaffold_845;HRSCAF=1060_pilon_pilon	18018563
Scaffold_2316;HRSCAF=2900_pilon_pilon	17107477
Scaffold_2312;HRSCAF=2896_pilon_pilon	16741216
Scaffold_53;HRSCAF=107_pilon_pilon	13520883
Scaffold_2319;HRSCAF=2903_pilon_pilon	12332728

**Comment by jebrosen** [comment]
As it turns out the very largest contig is usually or always not counted due to an edge case in the calculation.

We are working on a fix. Thanks for letting us know about this issue!

**Comment by jebrosen** [comment]
This bug is one of several that have been fixed in RepeatModeler 2.0.2, released this week. Thanks again for reporting this!
