### ISSUE TITLE
Can not locate file

### ISSUE THREAD

**Issue by Tdanis** [Dfam-consortium/RepeatModeler#59]
**Hello, so I am new user of RepeatModeler and I can not solve this problem .
Could someone help me please?
Thank you**

Using output directory = /mnt/scratch/tdanis/RepeatModeler/Default/RM_96911.TueJan211938302020
Storage Throughput = poor ( 122.02 MB/s )
  - NOTE: Poor storage througput will have a large impact on RepeatModeler
          performance.  The low throughput observed above may be due to
          transient usage patterns on the system and may not reflect the
          actual system performance. Whenever possible run RepeatModeler
          in a directory stored on a fast local disk and not over a
          network filesytem.

Ready to start the sampling process.
INFO: The runtime of RepeatModeler heavily depends on the quality of the assembly
      and the repetitive content of the sequences.  It is not imperative
      that RepeatModeler completes all rounds in order to obtain useful
      results.  At the completion of each round, the files ( consensi.fa, and
      families.stk ) found in:
      /mnt/scratch/tdanis/RepeatModeler/Default/RM_96911.TueJan211938302020/ 
      will contain all results produced thus far. These files may be 
      manually copied and run through RepeatClassifier should the program
      be terminated early.

RepeatModeler Round # 1
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 40000000 bp
   - Final Sample Size = 40008103 bp ( 40008103 non ambiguous )
   - Num Contigs Represented = 89
   - Sequence extraction : 00:00:04 (hh:mm:ss) Elapsed Time
 -- Running RepeatScout on the sequences...
   - RepeatScout: Running build_lmer_table ( l = 14 )..
   - RepeatScout: Running RepeatScout.. : 738 raw families identified
   - RepeatScout: Running filtering stage..RepeatScout filter-stage-1 failed:
Can't locate File/Which.pm in @INC (you may need to install the File::Which module) (@INC contains: /home1/tdanis/anaconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home1/tdanis/anaconda3/lib/site_perl/5.26.2 /home1/tdanis/anaconda3/lib/5.26.2/x86_64-linux-thread-multi /home1/tdanis/anaconda3/lib/5.26.2 .) at /mnt/big/Tools/RepeatScout-1.0.6/filter-stage-1.prl line 14.
BEGIN failed--compilation aborted at /mnt/big/Tools/RepeatScout-1.0.6/filter-stage-1.prl line 14.
Please see /mnt/scratch/tdanis/RepeatModeler/Default/RM_96911.TueJan211938302020/round-1/filter-stage-1.log for details.
(base) tdanis@hydrogen:/mnt/scratch/tdanis/RepeatModeler/Default$ cat /mnt/big/Tools/RepeatScout-1.0.6/filter-stage-1.prl

**Comment by jebrosen** [comment]
> Can't locate File/Which.pm in @inc (you may need to install the File::Which module)

The RepeatModeler `configure` script (at least the latest version) should have checked this already and shown an error message - which version of RepeatModeler is this?

I see you are using conda; you should probably either leave the conda environment (if `File::Which` is installed on the main system) or install `File::Which` into the conda environment (with `conda install perl-file-which`).

Note that the bioconda version of RepeatModeler has often been broken, but it does not look like you are using it so that should not be the problem.

**Comment by Tdanis** [comment]
Firstly thank you for your instant reply.  I have already try to `conda deactivate`  and it seams that there is no problem until now. Else I will try cond solution. It is the latest version.

Thank you again
