### ISSUE TITLE
RepeatModeler is showing no progress

### ISSUE THREAD

**Issue by devenderarora** [Dfam-consortium/RepeatModeler#61]
I am running RepeatModeler on genome data by following the help module. I am not seeing any progress since long time. I am trying to fix this issue but not found any success yet. 

In run.out file the progress stuck at:
RepeatClassifier Version 2.0
========================
Search Engine =rmblast
-Looking for Simple and Low complexity sequences..

Please let me know what wrong I am doing.
My command is ../RepeatModeler -database species -pa 20 -LTRStruct >& run.out &

**Comment by jebrosen** [comment]
Hi @devenderarora,

That step generally should not take a long time. To help troubleshoot, can you share with us:

* The versions of RepeatModeler, RepeatMasker, and TRF you are using
* Whether trf and RepeatMasker are still active and how long they have been running (e.g. with `top` or `ps aux | grep -iE 'trf|repeatmasker'`)
* RAM usage (`free` command) and disk usage (`df` command)

**Comment by devenderarora** [comment]
I am using RepeatModeler: 2.0, RepeatMasker : 3.0. The command is no more running as I assume from top command. RAM and disk space is not issue at the current moment. Is there any issue with the version I am using?

**Comment by jebrosen** [comment]
> RepeatMasker : 3.0

That is a very old version; over 12 years old. We definitely recommend using a newer version of RepeatMasker - the latest version is 4.1.0 and is available at http://www.repeatmasker.org/RMDownload.html

**Comment by devenderarora** [comment]
I apologise for the typo mistake. We are using RepeatMasker 4.1.0 and running with the same situation.

**Comment by jebrosen** [comment]
Is repeatmodeler (or repeatclassifier) still running now, according to `top`/`ps`, or the `jobs` command in the same shell where you started RepeatModeler from?

**Comment by devenderarora** [comment]
No. RepeatModeler is not running anymore. It just stop there. I tried with different species

**Comment by devenderarora** [comment]
Dear Jebrosen
We re-ran the assembled genome file of size ~3gb using command: 
./RepeatModeler -engine ncbi -database Sample >& run.out &
and stucked at same step. It has been 5 days and the job is still running on server. Although we can see the command is running on terminal and ~400% CPU usage by rmblastn. Is it normal to take long time to finish the step?

**Comment by jebrosen** [comment]
> and stucked at same step. It has been 5 days and the job is still running on server. Although we can see the command is running on terminal and ~400% CPU usage by rmblastn. Is it normal to take long time to finish the step?

No, this does not sound usual. Your original post said it was on the step "-Looking for Simple and Low complexity sequences..", which should not typically run rmblastn for so long. I would expect to see that on the later step "-Looking for similarity to known repeat consensi..." instead.

Would you be able to post your `run.out` log file? The statistics reported from each run might help us determine why it is taking so long to run on these particular files.

**Comment by devenderarora** [comment]
Dear Jebrosen
I have attached the output file but there is no "-Looking for similarity to known repeat" I able to found.

[run1.txt](https://github.com/Dfam-consortium/RepeatModeler/files/6119566/run1.txt)

**Comment by jebrosen** [comment]
>  -- Running TRFMask on the sequence...
> TRFMask requires TRF version 4.09 or above
>   - TRFMask time 00:00:00 (hh:mm:ss) Elapsed Time

This looks like a pretty significant problem (and it would make sense that this causes excessive usage of `rmblastn`). How did you configure and install RepeatModeler including TRF?

**Comment by devenderarora** [comment]
We installed and configured the application following http://www.repeatmasker.org/RepeatModeler/ instructions.
Do we need to re-configure TRF and re-run the steps?

**Comment by jebrosen** [comment]
> We installed and configured the application following http://www.repeatmasker.org/RepeatModeler/ instructions. Do we need to re-configure TRF and re-run the steps?

Yes, TRF (4.09 or later) needs to be installed and RepeatModeler configured with its location. But you should not have been able to finish `configure` the first time either if you did not have TRF installed, so that may not actually fix it. Please let us know if that doesn't solve the problem!

**Comment by devenderarora** [comment]
I just reconfigured and again run the command and this time 

TRFMask time 00:00:08 (hh:mm:ss) Elapsed Time

and Masked: 3.57%

I am still waiting for progress and will share my experience.
Thank you for pointing it out.

**Comment by devenderarora** [comment]
Dear Jebrosen
I tried with small genome to test if it works perfectly. I ran RepeatModeler on ecoli genome file and ended up at rmblast.
I will be grateful to you if I can understand where configuration is getting wrong. 
[ecoli1.txt](https://github.com/Dfam-consortium/RepeatModeler/files/6126876/ecoli1.txt)

**Comment by jebrosen** [comment]
That new error message looks familiar.... I think it is #111 . In that situation the genome is small enough that the final library had 0 elements (everything discovered was too low-complexity), and it shows the confusing error message about `tmpConsensi.fa.masked`.

The first log file only indicated that TRF was a problem, and TRF looks fine in the second run. So I would say that the configuration seems to be fixed now.

**Comment by devenderarora** [comment]
Thankyou so much. We re-ran the assembly and it just finished seems like configuration was not done rightly. 
Thankyou for the great help. 

Regards
Devender Arora

**Comment by jebrosen** [comment]
Glad to hear it it working for you! Looks like we can close this issue.

Best,
-Jeb
