### ISSUE TITLE
stop at round-6 without error message

### ISSUE THREAD

**Issue by njaupan** [Dfam-consortium/RepeatModeler#63]
Hi,
I have used RepeatModeler2 and updated RepeatMasker 4.0.9, but it stops at round-6 without any error message, three files in the folder round-6: sampleDB-6.fa.entry_batch, sampleDB-6.fa and tmpSample.fa. No more process shows.              
May i ask what is the problem? Is it finished?
Best,
pan

**Comment by jebrosen** [comment]
That sounds like a failed run; there should be more files than that. Do you have the output / logs from the run? They would help troubleshoot what went wrong.

You may be able to resume RepeatModeler by using the `-recoverDir` option on the command line, to avoid repeating all the previous rounds.

**Comment by njaupan** [comment]
Hi, I only have these files and run.out file:
RepeatModeler Round # 6                                                                        
========================                                                                     
Searching for Repeats                                                                        
 -- Sampling from the database...                                                              
   - Gathering up to 243000000 bp                                                              
   - Sequence extraction : 00:07:01 (hh:mm:ss) Elapsed Time                                
 -- Running TRFMask on the sequence... 
Now I have rerun RepeatModeler using -recoverDir and it seems working now.
