### ISSUE TITLE
The difference between the number of unclassified and unknown sequences in the output

### ISSUE THREAD

**Issue by xvtyzn** [Dfam-consortium/RepeatModeler#78]
Thank you for creating this great software.
I am analyzing the repeat sequence in the genomes of some insects.

This may be a fairly beginner question, but the number of unclassified sequences in the output file, example_final.fa.out, and example_final.fa.tbl does not match (input file is example_final.fa).

I was simply thinking that the total base length added to the sequence in example_final.fa.out where the class is Unknown is the same as Unclassified. However, perhaps this idea is wrong.

How do you calculate the unclassified sequences of the output file?

**Comment by jebrosen** [comment]
Based on your filenames, I think this is a question about RepeatMasker.

> example_final.fa.out, and example_final.fa.out does not match

These are the same file - which is the file that doesn't match?

I assume you are referring to the `.tbl` file. One of the biggest differences between `.out` and `.tbl` is that the base pair count in the `.tbl` file accounts for overlaps. The `.out` file can include overlapping annotations (marked with a `*`), so simply adding up the number of base pairs covered will be an overestimate.

**Comment by xvtyzn** [comment]
I apologize for the error in the question.
You're right about the difference between example_final.fa.out and example_final.fa.out.tbl.
My question was completely answered. Thank you!
