### ISSUE TITLE
RepeatModeler v 2.0.1 doesn't produce "consensi.fa.classified"

### ISSUE THREAD

**Issue by lucolotto** [Dfam-consortium/RepeatModeler#81]
Hi all,
I have recently installed RepeatModeler v2.0.1 (previously I used to have the version open-1.0.11). 
I used these commands to build a database and run repeatmodeler:

```
BuildDatabase -name $YOUR_DB_NAME -engine ncbi $YOUR_DB_NAME.fa    
RepeatModeler -engine ncbi -pa 200 -database $YOUR_DB_NAME 2>&1 | tee RepMod_run.log 

```
The run seems to finish successfully but the consensi.fa.classified file is not created....
So I checked the log file and the only strange thing I could spot was 

```
Missing /opt/conda3/envs/maker-2020.4/share/RepeatMasker/Libraries/RepeatMasker.lib.nsq!
Please rerun the configure program in the RepeatModeler directory
before running this script.
```

Could this missing file be the reason why I do not get the consensi.fa.classified file?
Can you help me fixing this? I used conda to install RepeatModeler.
Thanks
All the best
Luca

**Comment by jebrosen** [comment]
The error message has a typo - it says `in the RepeatModeler directory` when it should say `in the RepeatMasker directory`.

> Can you help me fixing this? I used conda to install RepeatModeler.

The issue here is that the conda recipe for `RepeatMasker` does not run the `configure` script. You need to (optionally) install RepBase RepeatMasker Edition and run `configure` in the RepeatMasker directory; after configuring the RMBlast search engine it will build the `RepeatMasker.lib.nsq` file needed by `RepeatModeler` for classification.

**Comment by lucolotto** [comment]
Thanks @jebrosen for your detailed reply!  I checked and I was missing this file. Luckily I had the file in the previous installation of RepeatModeler so I copied it in the `RepeatMasker/Libraries` path. I tried to run RepeatModeler and now it produces the "consensi.fa.classified" file!

Thanks for the hint! :D

**Comment by tkjmk** [comment]
I just wanted to add that I had the same problem. The program ran to completion, but no consensi.fa.classified was produced. This was my workaround.

I had installed RepeatMasker with conda in an environment that I called RM_env. The RepeatMasker binary can be found in:
`${PATH_TO_CONDA}/envs/RM_env/bin/`
This where I configured RepeatModeler to find the RepeatMasker binary.

However, the RepeatMasker/Libraries is not found here - when installed with conda this is found in the share directory:
`${PATH_TO_CONDA}/envs/RM_env/share/RepeatMasker/Libraries`

In RepeatMasker/Libraries I found the RepeatMasker.lib, and simply ran
`makeblastdb -dbtype nucl -in RepeatMasker.lib`
to generate the RepeatMasker.lib.nsq file.

Then with the output from my original 'successful' RepeatModeler run, 
I simply ran:
`RepeatClassifier -repeatmasker_dir ${PATH_TO_CONDA}/envs/RM_env/share/RepeatMasker/ -consensi ${cns_file} -stockholm ${stk_file}`

The repeatmasker_dir should be the RepeatMasker with the Libraries directory.

This output both: consensi.fa.classified and families-classified.stk.

**Comment by szzxpxf** [comment]
Thanks for bringing this up. I had the same issue with RepeatModeler installed via bioconda. Manually generating the RepeatMasker.lib.nsq solved the issue!

**Comment by madmolecularman** [comment]
I wanted to report on my experience with this. I also acquired RepeatModeler from conda and had a similar issue with a missing RepeatMasker library.  This may be repeated information but I hope to clarify an intermediate step in acquiring the RepeatMaskker library as I did not have a RepeatMasker.lib file nor a previous version.

When intially looking to the `/miniconda3/envs/RepeatModeler/share/RepeatMasker/Libraries` I did not find the `RepeatMakser.lib.nsq` file.  I took @jebrosen configure comment and ran with it. 

From `/miniconda3/envs/RepeatModeler/share/RepeatMasker` run:

`perl ./configure`

prompts 

```
Add a Search Engine:
	1. Crossmatch - Phrap                 [ Un-configured ]
	2. RMBlast - Improved NCBI blast      [ Un-configured ]
	3. HMMER3.1 & DFAM                    [ Un-configured ]
	4. ABBlast/WUBlast                    [ Un-configured ]
	
Enter Selection: 
```
Configured  selection 2 and 3. When configuring a selection a prompt may ask for the trf path and the paths of the other programs which is here:

TRF: `/miniconda3/envs/RPmodeler/bin/trf`
RMBlast & DFAM: `/miniconda3/envs/Repeatmodeler/bin`

If I check `/miniconda3/envs/RepeatModeler/share/RepeatMasker/Libraries` I now have the `RepeatMakser.lib.nsq` file and can proceed without the error.

After your done then you can run RepeatClassifier on the existing consensi.fa and families.stk files as other users have indicated.

**Comment by RNieuwenhuis** [comment]
I am puzzled..

I did follow the instructions as written by @madmolecularman after installing RepeatModeler through bioconda, however I get the missing `RepeatMakser.lib.nsq` message when running RepeatClassifier.

Configuring RMBlast and setting it as default gives the following message:
```
Add a Search Engine:
   1. Crossmatch: [ Un-configured ]
   2. RMBlast: [ Configured, Default ]
   3. HMMER3.1 & DFAM: [ Un-configured ]
   4. ABBlast: [ Un-configured ]

   5. Done


Enter Selection: 5
Building RMBlast frozen libraries..
The program is installed with a the following repeat libraries:
  Dfam database version Dfam_3.1
  RepeatMasker Combined Database: Dfam_3.1
Further documentation on the program may be found here:
  /home/WUR/nieuw133/miniconda3/envs/Repeat_modeler/share/RepeatMasker/repeatmasker.help
```

The result of  `ls /miniconda3/envs/Repeat_modeler/share/RepeatMasker/Libraries`
```
Artefacts.embl  Dfam.hmm                 RepeatMasker.lib      RepeatPeps.lib.pdb  RepeatPeps.lib.pot  RepeatPeps.lib.pto  taxonomy.dat
CONS-Dfam_3.1   README.meta              RepeatMaskerLib.embl  RepeatPeps.lib.phr  RepeatPeps.lib.psq  RepeatPeps.readme
Dfam.embl       RepeatAnnotationData.pm  RepeatPeps.lib        RepeatPeps.lib.pin  RepeatPeps.lib.ptf  RMRBMeta.embl
```

The RepeatMasker.lib file is empty.

Any clues on what is going on? @jebrosen

**Comment by jebrosen** [comment]
@RNieuwenhuis that is an old version of RepeatMasker from bioconda; the latest in bioconda is 4.1.1. However there is a separate bug affecting `RepeatClassifier` in that version, so the easier thing is probably to figure out what went wrong by doing it manually this time:

After a `cd` into `/miniconda3/envs/Repeat_modeler/share/RepeatMasker/Libraries`, try running `/miniconda3/envs/Repeat_modeler/bin/makeblastdb -dbtype nucl -in RepeatMasker.lib`. I hope `/miniconda3/envs/Repeat_modeler/bin/makeblastdb` is the right path to get to `makeblastdb` in your conda installation, but I'm not entirely sure. This program should either successfully make the `RepeatMasker.lib.nsq` etc. files, or it should explain what went wrong.

**Comment by RNieuwenhuis** [comment]
Thank you for you reply @jebrosen ,

I tried your suggestion, but the `RepeatMasker.lib` file is empty and will not produce a blast db. ~~How can I obtain it?~~

I did find this [thread](https://bioinformatics.stackexchange.com/questions/14634/how-to-fix-repeatmasker-lib-nsq-missing-error-when-running-repeatmodelorl) on StackExchange that shows me how to create RepeatMasker.lib and explains why it wasn't working. Is that correct?

If yes, I will test RepeatClassifier.

It does raise the question however, and please forgive me my ignorance if it is already documented somewhere, what is RepeatMasker.lib exactly? And how does it compare to Dfam and RepBase. Why would I want to choose one over the other? 

Thanks for helping me out!

**Comment by jebrosen** [comment]
> I did find this thread on StackExchange that shows me how to create RepeatMasker.lib and explains why it wasn't working. Is that correct?

In general I don't recommend following threads such as those if there is better support available, since the details are specific to certain versions of the programs that you may or may not actually be using. Instead, I would try this:

* Install the latest version, RepeatMasker 4.1.1 (via conda or otherwise) and its dependencies (the python library `h5py` is a new dependency). This way we are sure you are using a specific and recent version, and if you still have issues we will have a better chance at actually fixing them in future versions of the program.
* `cd` into the `.../share/RepeatMasker` directory, and run this command to work around the bug I referred to in RepeatMasker 4.1.1: `./famdb.py -i ./Libraries/RepeatMaskerLib.h5 families --descendants 1 --curated --format fasta_name --include-class-in-name > ./Libraries/RepeatMasker.lib`
* Run `makeblastdb -dbtype nucl Libraries/RepeatMasker.lib` again, and make note of any errors
* Run `RepeatClassifier` again

> It does raise the question however, and please forgive me my ignorance if it is already documented somewhere, what is RepeatMasker.lib exactly? And how does it compare to Dfam and RepBase. Why would I want to choose one over the other?

`RepeatMasker.lib` is simply a copy of the configured RepeatMasker libraries (Dfam by default, and optionally also RepBase) in FASTA format. The file is mainly used by `RepeatClassifier`, during the classification step that compares putative discovered TE families to already-known TE sequences. It is not normally supposed to be something a user would ever have to worry about, but at different times there have been problems with our software, `makeblastdb`, or bioconda's packaging that cause issues for some users.

**Comment by RNieuwenhuis** [comment]
Thanks for clarifying, I see how I got confused. 

I will remove the link to the thread then, your explanation is very comprehensive.

Thanks again!

**Comment by gill0110** [comment]
@RNieuwenhuis  Hi, I met a similar problem - the RepeatMasker.lib file is empty . I have tried the suggestions mentioned above, but it did not work. How did you solve the problem ? THANKS !
