### ISSUE TITLE
NCBIBlastSearchEngine::search: Error...query RM_39391.MonMay181604012020/round-2/batch-35.fa) does not exist!

### ISSUE THREAD

**Issue by U201412486** [Dfam-consortium/RepeatModeler#82]
Hi,
    when I run RepeatModeler,it reports the error below.
     `NCBIBlastSearchEngine::search: Error...query (/repeatModeler3/RM_39391.MonMay181604012020/round-2/batch-35.fa) does not exist!
NCBIBlastSearchEngine::search: Error...query (repeatModeler3/RM_39391.MonMay181604012020/round-2/batch-37.fa) does not exist!
NCBIBlastSearchEngine::search: Error...query (RM_39391.MonMay181604012020/round-2/batch-38.fa) does not exist!
NCBIBlastSearchEngine::search: Error...query (RM_39391.MonMay181604012020/round-2/batch-40.fa) does not exist!
NCBIBlastSearchEngine::search: Error...query (RM_39391.MonMay181604012020/round-2/batch-39.fa) does not exist!
`
What does the error mean ?
sun,

**Comment by jebrosen** [comment]
Hi, sorry you are running into an error.

Can you post the contents of `/home/sunxh/project/annotation_gouqi/repeatModeler3/RM_39391.MonMay181604012020/round-2/blastdbcmd.log`? That file should contain additional information about the problem.

**Comment by U201412486** [comment]
I am sorry to tell you the file of `repeatModeler3/RM_39391.MonMay181604012020/round-2/blastdbcmd.log` is empty after the run.

**Comment by jebrosen** [comment]
What kind of filesystem is this, and is there plenty of free space? Do any of those `batch-x.fa` files listed in the error message exist, and do they have contents or are they empty?

**Comment by U201412486** [comment]
I ran the code again.Strangely,it successed this time.

**Comment by jebrosen** [comment]
That is strange. This sounds like it could be a temporary error, and you were just unlucky this run - an unfortunately frequent problem especially in some environments such as compute clusters or low-memory. It could also be a rare corner case with a specific part of the input sequence, and as RepeatModeler uses a randomized sampling approach the "problem" sequence was not used in your successful run.

Please re-open with more details if you see the same issue again!
