### ISSUE TITLE
Missing RepeatMasker.lib.nsq and Dfam use

### ISSUE THREAD

**Issue by pedrobdfp** [Dfam-consortium/RepeatModeler#83]
Hi!

I am currently annotating a non-reference species genome, and I am applying RepeatModeler and RepeatMasker. I installed them with miniconda (BioBuilds).

I run RepeatModeler, which did not yield me a classified uotput, so I tried to do it by running

RepeatClassifier -consensi consensi.fa

However, I got the following error:
Missing {PATH}/RepeatMasker/Libraries/RepeatMasker.lib.nsq

In this threat, the developer suggests downloading and applying the RepBase.
https://github.com/bioconda/bioconda-recipes/issues/9988

However, RepBase is NOT free anymore, requiring a very expensive subscription my university is unable to afford at the moment.

How can I get RepeatModeler to use Dfam database instead? I checked, It is already within {PATH}/RepeatMasker/Libraries

Thanks!
Pedro

**Comment by tkjmk** [comment]
Hey Pedro,
I have been using RepeatClassifier with the Dfam library. Although, RepeatClassifier does not seem to use nhmmer.

I think you'll find your solution in this closed issue https://github.com/Dfam-consortium/RepeatModeler/issues/81 

It's to do with using RepeatMasker from a conda installation. Briefly, you have to run makeblastdb on the RepeatMasker.lib, and then run RepeatClassifier with `-repeatmasker_dir` followed by the path to the RepeatMasker directory that has your Libraries directory in it.

**Comment by pedrobdfp** [comment]
I had tried that but the RepeatMasker.lib file is not a fasta file, so I cant run makeblastdb with it.

**Comment by pedrobdfp** [comment]
Also, when I try to go do ./configure within the RepeatMasker directory after downloading Dfam.hmm into the Libraries directory, this happens:

BEGIN failed--compilation aborted at /home/pb21/miniconda3/envs/repeat/share/RepeatMasker/LibraryUtils.pm line 61.
Compilation failed in require at ./configure line 66.
BEGIN failed--compilation aborted at ./configure line 66.

**Comment by jebrosen** [comment]
> BEGIN failed--compilation aborted at /home/pb21/miniconda3/envs/repeat/share/RepeatMasker/LibraryUtils.pm line 61.

line 61 of `LibraryUtils.pm` is `use Data::Dumper;`, and `Data::Dumper` is part of perl. So I am really not sure why you would get that error. Perhaps conda packages it separately, as `perl-data-dumper`?

**Comment by pedrobdfp** [comment]
Hi!

I am using a fresh CentOs 7 install, which is what the university game me, and this problem was solved by doing this:
sudo yum install perl-version perl-Data-Dumper

But now I am stuck in a forever loop when I do the ./configure. It keeps asking me these:

"""
add a Search Engine:
   1. Crossmatch - Phrap             [ Un-configured ]
   2. RMBlast - Improved NCBI Blast  [ Configured, Default ]
   3. HMMER3.1 & DFAM                [ Un-configured ]
   4. ABBlast/WUBlast                [ Un-configured ]

   5. Done

Enter Selection:           

**RMBlast (rmblastn) INSTALLATION PATH**

  This is the path to the location where
  the rmblastn and makeblastdb programs can be found.         
"""  

I enter the correct path, but it just loops back around to the first question. Help?

**Comment by jebrosen** [comment]
> I enter the correct path, but it just loops back around to the first question. Help?

Which question is the "first" question it loops back to? Once you have selected "Done", `configure` should build a few database files (if necessary) and exit without any more prompts.

**Comment by jebrosen** [comment]
If you do not want to configure any other search engines, you should select option "5. Done".

**Comment by pedrobdfp** [comment]
Thank you!  I appreciate your time!. I knew I was probably doing something silly.

I got this message:
Congratulations!  RepeatMasker is now ready to use.
The program is installed with a the following repeat libraries:
  Dfam database version Dfam_3.1
  RepeatMasker Combined Database: Dfam_3.0

But now, when I run 

RepeatClassifier -consensi consensi.fa

I get this message:

No database indicated or it is an empty file.

How do I specify the database? I cannot find this option on the -help page.

**Comment by pedrobdfp** [comment]
Yes I checked. It is a 3.0 M file that I got as an output of running RepeatModeler.

Here is the head to that file:

>rnd-1_family-67 ( RepeatScout Family Size = 866, Final Multiple Alignment Size = 100, Localized to 8596 out of 11716 contigs )
TCAGGGTGGCGATTCGGCGGACGATTTCAAATTCCCGGTCATTTCCCGGTTCTTCACGGTCAAGTTTTTCAATTTTCCCGGTCAACTAGAAGTAACATATTTATATTTGTCGCAAAACGCNAACATTTATTTTTATTCATGACGTTCATTCTAAACATCCTTTAACACAACAGATCAAACATTGCAAAATAAATCAATTTTGAAAAGAATACTCNAATTTTCAACAAAAAAATATCATTTTTTTACAAAAATTGGAACAGTTAAACTTACAATTAAAAAAATCAATTTACGATAACAAAAAAAAAAACGGATTTCCAACAAAATAGTTCATTTTTCAACCAATGTGATGAATTTTCAAATAANANNATGAATCTTCAACCGGAACANTTAAATTTCAAAACAAGAAGATGAATTTTCAACTAAAAAGATAAATATTTAACTGGAGCACTTCAATTTCCAACCATGAAGGTGAATATTCAAACAAGAAGATTAATTTCCAAATAGAAAGAATCATTTTCTAAGAAAAAATATAA

>rnd-1_family-357 ( RepeatScout Family Size = 116, Final Multiple Alignment Size = 100, Localized to 8596 out of 11716 contigs )
TTATTTTTACACTGAGCGGGTCACCAGTCCGCTGCAGGAATCTGATAAAAATTCTTATNAACTGCTCAAATAAGAGCTAGTCGAATTTTGAGACTATCAGTTTTTACACAAAAAATATTAGACNATTGGACTTCATAAAAATTTGAAAAA

>rnd-1_family-301 ( RepeatScout Family Size = 142, Final Multiple Alignment Size = 100, Localized to 8596 out of 11716 contigs )
ATAATATTTGCCCTTTTAAATTGCCCTTGAATTTTATTNAGTAGATGAATTGTTTTCTTGTTGGAAATTCGTATTTTTCGCGGTTACACTTGGAAATTTCCTTGCAAATTCATGCT

>rnd-1_family-250 ( RepeatScout Family Size = 182, Final Multiple Alignment Size = 100, Localized to 8596 out of 11716 contigs )

**Comment by pedrobdfp** [comment]
Oddly enough, repeating the command after rebooting the machine worked. Go figure.

Thank you very much again for your time in solving this issue!

**Comment by pedrobdfp** [comment]
Hi!

Yeah, I tought it had been soved. However, after running for a couple hours, it stopped again and complained I should have run ./configure in the RepeatModeler directory, not in the RepeatMasker directory like I did above.

But when I run

perl ./configure ,

After inserting several paths, I get this:

fileparse(): need a valid pathname at /home/pb21/miniconda3/envs/repeat/share/RepeatModeler/RepModelConfig.pm line 246.

I am sorry, did I make something silly again?

**Comment by jebrosen** [comment]
I know of at least one error message that says "run configure in the RepeatModeler directory" that is supposed to say "run configure in the RepeatMasker directory". Can you post the whole log file from a failed run?

**Comment by pedrobdfp** [comment]
Sure. When it run it did not generate any output files or logs. How can I get it to?

**Comment by jebrosen** [comment]
Sorry, the output to the screen is what I meant in that message.

**Comment by pedrobdfp** [comment]
Alright, I am seeing a pattern here. I had not recorded the full message, so I rerun it to get the complete message. The message had happened soon after the last of these lines appeared:

>RepeatClassifier Version 2.0.1
>======================================
>Search Engine = rmblast
> - Looking for Simple and Low Complexity sequences..
>  - Looking for similarity to known repeat proteins..
>  - Looking for similarity to known repeat consensi..

However, funny enough, this time the program run entirely with no bug message, and generated a .classified output.

I am not sure what is up, but I have a hint:
The first time I run ./configure and got the error message i pasted in the previous message, I had forgotten to activate the conda module for RepeatModuler. Then, I got this message:

>The following perl modules required by RepeatModeler are missing >from
>your system.  Please install these first:
>    JSON
>    File::Which
>    URI
>    LWP::UserAgen

I realized that, activated the conda module, rerun ./configure and got the message I had pasted above:

fileparse(): need a valid pathname at /home/pb21/miniconda3/envs/repeat/share/RepeatModeler/RepModelConfig.pm line 246.

..
So I believe the problem here must be some odd incompatibility between the perl version installed in my computer and the one that comes along in conda

In the meantime (while I waited for your answer), I tried fizing the error I had gotten before in case it had something to do.

I had to do these:

sudo yum install perl perl-JSON
sudo yum install perl perl-File-Which
sudo yum install perl perl-URI
sudo yum install perl perl-libwww-perl

--
So, I believe the reason it worked now is probably related to the fact I did these modifications to my perl instalation.

Anyways, thanks a lot for all your time!

**Comment by jebrosen** [comment]
> So I believe the problem here must be some odd incompatibility between the perl version installed in my computer and the one that comes along in conda

Yes, mixing environments often causes problems like these. We generally recommend installing without using conda, but the conda packaging is going in the direction of working properly "out of the box" for `RepeatModeler`.

It sounds like things are working now - if you have more trouble, please re-open this or a new issue!
