### ISSUE TITLE
Error running repeatModeler

### ISSUE THREAD

**Issue by bioinfo-Kacst** [Dfam-consortium/RepeatModeler#84]
All the configuration and dependencies are in the right place.

running BuildDatabase passed.
but Running RepeatModeler an error occurs please advice :
```
Can't locate WUBlastSearchEngine.pm in @INC (you may need to install the WUBlastSearchEngine module) (@INC contains: /usr/local/bin /Users/ohon_ad/Documents/Tools/RepeatModeler-master /usr/local/lib/perl5/site_perl/5.28.2/darwin-2level /usr/local/lib/perl5/site_perl/5.28.2 /usr/local/lib/perl5/5.28.2/darwin-2level /usr/local/lib/perl5/5.28.2 /usr/local/lib/perl5/site_perl) at /Users/ohon_ad/Documents/Tools/RepeatModeler-master/RepeatUtil.pm line 78.
BEGIN failed--compilation aborted at /Users/ohon_ad/Documents/Tools/RepeatModeler-master/RepeatUtil.pm line 78.
Compilation failed in require at RepeatModeler line 126.
BEGIN failed--compilation aborted at RepeatModeler line 126.
```

**Comment by jebrosen** [comment]
Was this solved? If you can share what you did to fix it that would help the next person who has the problem.

**Comment by Daniel-Ze** [comment]
The solve would be a great help here!

Installed RepeatModeler 2.0.1 with conda:

conda create -n repmod2 repeatmodeler=2.0.1

Ran the ./configure script from within envs/repmod2/share/RepeatModeler folder and everything was detected.

**Comment by Daniel-Ze** [comment]
The only thing that worked for me was to install all dependencies in a conda environment and installing RepeatModeler 2.0.1 and RepeatMasker 4.1.0 downloaded from GitHub separately (not with conda) and linking all dependencies of the two configure scripts to the conda environment.
