### ISSUE TITLE
error in multi threads when I use " -LTRStruct "

### ISSUE THREAD

**Issue by longzhangnation** [Dfam-consortium/RepeatModeler#88]
Hi,
  I am using the output of RepeatModeler  for my downstream analysis  . I compile the RepeatModeler mannually bacause I don't have the root access . After compiling the GenomeTools with `make threads=yes cairo=no ` , and it finished . At last , every  software was prepared well . I use the command `RepeatModeler -database $basenma -pa 34  -LTRStruct` for the software after the database builted . After that , the first 6 rounds finished in 1 day , but it stopped at LtrHarvest . I noticed that it only consume one CPU eventhough  I set  -aparallel to 34 . Even I ran the software  solely `gt -j 30 ltrharvest -index ../RM_6658.SatJun201049522020/LTR_122470.SunJun212131462020/LHAR_122470.SunJun212131462020/esa_index
-out ltr_out` , the CPU used is only 1 . 
  So I am going to drop the `-LTRStruct` and rerun it with the command `RepeatModeler -database $model -pa 34 -recoverDir RM_6658.SatJun201049522020` . Before rerunning it , I did `mv  round-6/consensi.fa  round-6/consensi.fa.bak` and soon  start reruning the command above . Do I do right ? Or should I reastart the software ?

**Comment by jebrosen** [comment]
At least one step of LTRHarvest [was actually broken](https://github.com/genometools/genometools/issues/922) with multithreading, so it's specifically disabled. I'm not sure why `ltrharvest` alone still only uses 1 CPU, though.

> Before rerunning it , I did mv round-6/consensi.fa round-6/consensi.fa.bak and soon start reruning the command above . Do I do right ? Or should I reastart the software ?

Neither of those should be necessary: the only remaining step without LTRStruct would have been `RepeatClassifier`. The files `consensi.fa` and `families.stk` in the `RM_<date>` directory can be run through `RepeatClassifier` directly as so:

`RepeatClassifier -consensi consensi.fa -stockholm families.stk`

**Comment by longzhangnation** [comment]
Thank you . I will do it right away.
