### ISSUE TITLE
TRF

### ISSUE THREAD

**Issue by mylena-s** [Dfam-consortium/RepeatModeler#90]
Hi,
Im writting to ask you something about TRF in RepeatModeler2.
Im interested in running TRF to predict Tandem repeats including Satellites in a genome, and as I already ran RepeatModeler, I wanted to know if TRF Is used in RM to construct tandem repeat models or if it is only used to mask these kind of sequences before running other programs. And also I would like to know (if it is possible) which parameters are used for the TRF runs in RM.

Thanks in advanced
Mylena

**Comment by jebrosen** [comment]
Hello,

TRF is currently used in a few places in RepeatModeler:

* In the first round (RepeatScout), RepeatModeler uses `filter-stage-1.prl` from the RepeatScout package. This script calls TRF with the parameters `2 7 7 80 10 50 500`, and models that are seen as "too repetitive" or too low-complexity do not go on to become models.
* In subsequent rounds (RECON), RepeatModeler uses TRF to mask the input sequence before doing the all-vs-all sequence comparison for RECON. This masking stage also uses the parameters `2 7 7 80 10 50 500`: https://github.com/Dfam-consortium/RepeatModeler/blob/master/TRFMask#L145

I hope this answers your questions.

**Comment by mylena-s** [comment]
Thank you very much for the help!

Cheers
Mylena
