### ISSUE TITLE
Unable to find final files

### ISSUE THREAD

**Issue by acontrerasg** [Dfam-consortium/RepeatModeler#92]
Hello there, 

I am able to run RepeatModeler2 and it seems that finished correctly. LTRpipeline and RepeatClassifier do not complain.  However, I do not obtain the  two final files: 
```
      <database_name>-families.fa
      <database_name>-families.stk
```

Despite being said in the run.log file that they have been saved. 

Instead inside of the RM folder I got a consensi.fa and a families.stk.

Any thoughts why  this is the case?

Thanks!

**Comment by jebrosen** [comment]
Those files are copies of `consensi.fa.classified` and `families-classified.stk` in the `RM` directory, and normally they are put into the working directory where `RepeatModeler` was started from. Can you post your `run.log` file, especially near the end?

**Comment by acontrerasg** [comment]
Sorry it took me long to answer, 

yes I can:

>run.out

RepeatScout/RECON discovery complete: 1586 families found


LTR Structural Analysis
=======================
Running LtrHarvest...     : 00:23:54 (hh:mm:ss) Elapsed Time
Running Ltr_retriever...  : 00:20:03 (hh:mm:ss) Elapsed Time
Aligning instances...     : 04:39:07 (hh:mm:ss) Elapsed Time
Clustering...             : 00:01:10 (hh:mm:ss) Elapsed Time
Refining families...      : 00:24:45 (hh:mm:ss) Elapsed Time
Program Time: 05:48:59 (hh:mm:ss) Elapsed Time
  -- Clustering results with previous rounds...
       - 1586 RepeatScout/RECON families
       - 1135 LTRPipeline families
       - Removed 361 redundant LTR families.
       - Final family count = 2360
LTRPipeline Time: 05:49:33 (hh:mm:ss) Elapsed Time


RepeatClassifier Version 2.0.1
======================================
Search Engine = rmblast
  - Looking for Simple and Low Complexity sequences..
  - Looking for similarity to known repeat proteins..
Classification Time: 00:02:35 (hh:mm:ss) Elapsed Time


Program Time: 22:42:27 (hh:mm:ss) Elapsed Time
Working directory:  /temp/RM_7678.FriJul31512082020
may be deleted unless there were problems with the run.

The results have been saved to:
  genome.fasta-families.fa  - Consensus sequences for each family identified.
  genome.fasta-families.stk - Seed alignments for each family identified.

The RepeatModeler stockholm file is formatted so that it can
easily be submitted to the Dfam database.  Please consider contributing
curated families to this open database and be a part of this growing
community resource.  For more information contact help@dfam.org.

**Comment by jebrosen** [comment]
This looks like a completely successful run... if at least one model is made then RepeatModeler copies the files and prints that information message, so I don't see any reason for it to not copy the files. What was the current working directory when you ran `RepeatModeler`?

Are the originals (`consensi.fa.classified` and `families-classified.stk`) still in `/temp/RM_7678.FriJul31512082020`?

**Comment by acontrerasg** [comment]
The working directory was the same where RM temp folder was created. I also tried to find it with bash command `find / -name 'genome.fasta-families.fa'` and I couldnt retrieve it .
Yes ,The  originals are still there.  I was just wondering if I can use consensi.fa.classified and families-classified.stk as the final version or there is something I am missing. 

Thanks again!

**Comment by jebrosen** [comment]
It sounds like this is resolved for now. If you experience a similar problem with the files not being copied again, please feel free to re-open this issue!
