### ISSUE TITLE
large genome in scanning TEs with the parameter `-LTRStruct` 

### ISSUE THREAD

**Issue by zoukai3412085** [Dfam-consortium/RepeatModeler#96]
We run into a problem after running for 5 days with the parameter `-LTRStruct` in scanning a ~9Gb genome.  No `families.fa` file was output in the home directory while the file `families.stk` existed in the subdirectory (figure2). 

Home directory to run Repeat Modeler：

![QQ截图20200805183148](https://user-images.githubusercontent.com/32789467/89404289-4bf42800-d74c-11ea-9b84-021d54a514e2.png)

The subdirectory to run Repeat Modeler（RM_24425.ThuJul300959262020）：

![222](https://user-images.githubusercontent.com/32789467/89404301-50204580-d74c-11ea-98bd-a476c01ff725.png)

the part of the run log is just as follows (approaching to the end of the run):

```
.......................................................
Processing RECON family: 2219
  - Saving 16 elements
  - Refining family-2219 model...

Processing RECON family: 3317
  - Saving 16 elements
  - Refining family-3317 model...
Family Refinement: 02:37:02 (hh:mm:ss) Elapsed Time
Round Time: 28:34:06 (hh:mm:ss) Elapsed Time

RepeatScout/RECON discovery complete: 2535 families found


LTR Structural Analysis
=======================
Running LtrHarvest...     : 06:15:19 (hh:mm:ss) Elapsed Time
Running Ltr_retriever...ERROR: LTRPipeline::runLtrRetriever : LTR libraries ( redundant: 37169, non-redundant: 11260 ) are larger than permissible threshold 10000 ).  See /home/zoukai/Documents/Endophyte/Ginkgo/RepeatModeler/RM_24425.ThuJul300959262020/LTR_7813.SatAug10907272020/LRET_7813.SatAug11522462020 for details.
LTRPipeline: No results after LTR_Retriever filtering.
LTRPipeline Time: 86:06:14 (hh:mm:ss) Elapsed Time


RepeatClassifier Version 2.0.1
======================================
Search Engine = rmblast
  - Looking for Simple and Low Complexity sequences..
  - Looking for similarity to known repeat proteins..
  - Looking for similarity to known repeat consensi..
Missing /home/zoukai/miniconda3/envs/RepeatModeler/share/RepeatMasker/Libraries/RepeatMasker.lib.nsq!
Please rerun the configure program in the RepeatModeler directory
before running this script.
Classification Time: 02:05:35 (hh:mm:ss) Elapsed Time


Program Time: 135:18:15 (hh:mm:ss) Elapsed Time
Working directory:  /home/zoukai/Documents/Endophyte/Ginkgo/RepeatModeler/RM_24425.ThuJul300959262020
may be deleted unless there were problems with the run.

The results have been saved to:
  gb-families.fa  - Consensus sequences for each family identified.
  gb-families.stk - Seed alignments for each family identified.

The RepeatModeler stockholm file is formatted so that it can
easily be submitted to the Dfam database.  Please consider contributing
curated families to this open database and be a part of this growing
community resource.  For more information contact help@dfam.org.

```

**Comment by jebrosen** [comment]
> `Running Ltr_retriever...ERROR: LTRPipeline::runLtrRetriever : LTR libraries ( redundant: 37169, non-redundant: 11260 ) are larger than permissible threshold 10000 ).  See /home/zoukai/Documents/Endophyte/Ginkgo/RepeatModeler/RM_24425.ThuJul300959262020/LTR_7813.SatAug10907272020/LRET_7813.SatAug11522462020 for details.`

The LTR analysis is computationally intensive with many putative LTRs, which is why you are seeing this message - @rmhubley, any ideas for dealing with this problem?

The current results (in `consensi.fa` and `families.stk`) will be based on the `RepeatScout`/`RECON` pipeline, as if you had not run with `LTRStruct`.

> ```
> Missing /home/zoukai/miniconda3/envs/RepeatModeler/share/RepeatMasker/Libraries/RepeatMasker.lib.nsq!
> Please rerun the configure program in the RepeatModeler directory
> before running this script.
> ```

This is probably the reason you do not get the final results as expected. The message here has a typo: the `configure` program in the *RepeatMasker* directory is the one that needs to be run. You do not need to re-run the entire RepeatModeler pipeline after fixing this; only `RepeatClassifier` would need to be re-run.

**Comment by zoukai3412085** [comment]
Thank you so much! The problem has been solved.
