### ISSUE TITLE
RepeatModeler2 failing on round2 all-by-other

### ISSUE THREAD

**Issue by jamesdgalbraith** [Dfam-consortium/RepeatModeler#98]
I'm trying to run RepeatModeler2 on several genomes and while it completes round 1 it is unable to complete the all-by-other comparisons of round 2 with the following error message:

```
FATAL ERROR: RepeatModeler giving up. One or more
batches failed!  Unfortunately this type of error
cannot be recovered from. Please submit the following
details to the feedback page at the repeatmasker
website:

       http://www.repeatmasker.org

RepeatModeler Version: 2.0.1
Search Engine: rmblast [ 2.10.0+ ]
Command Line: /home/a1194388/bin/RepeatModeler-2.0.1/RepeatModeler-database Ornithorhynchus_anatinus -pa 30 -LTRStruct
Batch Number: 5
Disk Space:
Filesystem                                       1K-blocks        Used     Available Use% Mounted on
10.34.46.201@o2ib2,10.34.46.202@o2ib2:/hpcfs 1981563177600 30562482532 1851080942032   2% /hpcfs

System Memory:
MemTotal:       197728448 kB
MemFree:        64971840 kB
MemAvailable:   67258172 kB
Cached:          4192520 kB
SwapCached:        80236 kB
SwapTotal:       7811068 kB
SwapFree:              0 kB
Further details about this problem may be found in
the directory: /hpcfs/users/a1194388/MammalRM/Ornithorhynchus_anatinus/RM_91708.MonAug171851172020
```

Looking within the round 2 folder the following error is in one of the ncResults*.err messages, while all other ncResults*.err messages contain no text.
```
Error: NCBI C++ Exception:
    T0 "/home/jrosen/code/RMBlast/ncbi-blast-2.10.0+-src/c++/src/corelib/ncbifile.cpp", line 5705: Error: ncbi::CMemoryFileMap::CMemoryFileMap() - To be memory mapped the file must exist: ''
```
All ncResults*.out files contain the expected BLAST alignments with the exception of the one corresponding to the error above.

Do you know what is causing this bug or how to resolve this?

**Comment by jebrosen** [comment]
Is this occurring on multiple genomes, and/or on the same genome more than once? Can you post the full log output from a failed run?

**Comment by jamesdgalbraith** [comment]
Unfortunately I've deleted the run and it's associated data due to space constraints. I've just finished running RepeatModeler in a custom Anaconda environment and the issue hasn't occurred again. If it does I'll save the data and upload it.

**Comment by goodgodric28** [comment]
I am having a similar issue, which appears to be a memory problem: 

` -- Input Database Coverage: 3020628 bp out of 1515217215 bp ( 0.20 % )
Sampling Time: 00:02:17 (hh:mm:ss) Elapsed Time
Running all-by-other comparisons...
        2% completed,  00:19:59 (hh:mm:ss) est. time remaining.
        4% completed,  00:10:08 (hh:mm:ss) est. time remaining.
        7% completed,  00:7:17 (hh:mm:ss) est. time remaining.
sh: /bin/cat: Argument list too long
        8% completed,  00:6:00 (hh:mm:ss) est. time remaining.
       10% completed,  00:5:14 (hh:mm:ss) est. time remaining.
WARNING: Retrying batch ( 24 ) [ 0 ]...
WARNING: Retrying batch ( 25 ) [ 0 ]...
       12% completed,  00:4:42 (hh:mm:ss) est. time remaining.
WARNING: Retrying batch ( 26 ) [ 0 ]...
       14% completed,  00:4:29 (hh:mm:ss) est. time remaining.
WARNING: Retrying batch ( 27 ) [ 0 ]...
WARNING: Retrying batch ( 28 ) [ 0 ]...
WARNING: Retrying batch ( 24 ) [ 0 ]...
sh: line 1: 129357 Segmentation fault      /home/sluglife/programs/rmblast-2.10.0/bin/blastdbcmd -db /oasis/projects/nsf/ddp370/sluglife/berghia_genome/dovetail_hic_Aug2020/Berghia_Aug2020_purgedups/repeatmodeler/RM_40182.MonJan251233542021/round-2/sampleDB-2.fa.masked -entry "gi|31" >> /oasis/projects/nsf/ddp370/sluglife/berghia_genome/dovetail_hic_Aug2020/Berghia_Aug2020_purgedups/repeatmodeler/RM_40182.MonJan251233542021/round-2/batch-30.fa 2>> /oasis/projects/nsf/ddp370/sluglife/berghia_genome/dovetail_hic_Aug2020/Berghia_Aug2020_purgedups/repeatmodeler/RM_40182.MonJan251233542021/round-2/blastdbcmd.log
WARNING: Retrying batch ( 25 ) [ 0 ]...
WARNING: Retrying batch ( 29 ) [ 0 ]...
       17% completed,  00:4:32 (hh:mm:ss) est. time remaining.
WARNING: Retrying batch ( 26 ) [ 0 ]...
WARNING: Retrying batch ( 30 ) [ 0 ]...
       18% completed,  00:4:17 (hh:mm:ss) est. time remaining.
WARNING: Retrying batch ( 27 ) [ 0 ]...
       21% completed,  00:4:00 (hh:mm:ss) est. time remaining.
WARNING: Retrying batch ( 28 ) [ 0 ]...
       23% completed,  00:3:47 (hh:mm:ss) est. time remaining.


FATAL ERROR: RepeatModeler giving up. One or more
batches failed!  Unfortunately this type of error
cannot be recovered from. Please submit the following
details to the feedback page at the repeatmasker

RepeatModeler Version: 2.0.1
Search Engine: rmblast [ 2.10.0+ ]
Command Line: /home/sluglife/programs/RepeatModeler/RepeatModeler-database Berghia_Aug2020_purged -pa 24 -LTRStruct
Batch Number: 24
Disk Space:

System Memory:
MemTotal:       1585293480 kB
MemFree:        1294664108 kB
MemAvailable:   1298156236 kB
Cached:          5941428 kB
SwapCached:            0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Further details about this problem may be found in
the directory: /oasis/projects/nsf/ddp370/sluglife/berghia_genome/dovetail_hic_Aug2020/Berghia_Aug2020_purgedups/repeatmodeler/RM_40182.MonJan251233542021


slurmstepd: Exceeded step memory limit at some point.
slurmstepd: Exceeded job memory limit at some point`

This is on one ~1.5 Gb genome with ~1100 scaffolds and an estimated 35% repeats (using GenomeScope). Any suggestions?
